#!/bin/bash
# Copyright (c) 2012 CIYAM Open Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 -o $# -gt 3 ]; then
 echo Usage: ciyam_backup [[-trunc]] [app name] [[web path]]
else
 opt=
 export CIYAM_STORAGE=$1
 web_path=$2
 backup_path=$PWD

 if [ "$1" = "-trunc" ]; then
  opt=$1
  export CIYAM_STORAGE=$2
  web_path=$3
 fi

 echo Starting backup...
 echo \<ciyam_backup.cin $opt>~ciyam_backup.cin
 ./ciyam_client -quiet -no_prompt <~ciyam_backup.cin
 rm ~ciyam_backup.cin

 if [ ! "$web_path" = "" ]; then
  pushd $web_path
  echo Adding application files to backup...
  ./bundle -q -y "$backup_path/$CIYAM_STORAGE.backup.bun.gz" -r files/*
  popd
 fi

 echo Finished backup...
fi
