#! /bin/sh
#
# ciyam_server startup/shutdown
#

### BEGIN INIT INFO
# Provides:          ciyamd
# Required-Start:    $network
# Required-Stop:
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: ciyam_server daemon
# Description:       CIYAM Service
### END INIT INFO

# Load the rc.status script for this service.
. /etc/rc.status

# Reset status of this service
rc_reset

CIYAMD_BIN=/usr/bin/ciyam_server
test -x $BAR_BIN ||
{
 echo "$BAR_BIN not installed";
 if [ "$1" = "stop" ]; then
  exit 0;
 else
  exit 5;
 fi;
}

case "$1" in
 start)
  echo -n "Starting ciyam_server "
  /sbin/startproc $CIYAMD_BIN -daemon -chdir=/home/ian/ciyam
  rc_status -v
  ;;

 stop)
  echo -n "Shutting down ciyam_server "
  killproc -TERM $CIYAMD_BIN
  rc_status -v
  ;;

 restart)
  $0 stop
  $0 start
  rc_status
  ;;

 status)
  echo -n "Checking for service ciyam_server "
  # Return value is slightly different for the status command:
  # 0 - service up and running
  # 1 - service dead, but /var/run/  pid  file exists
  # 2 - service dead, but /var/lock/ lock file exists
  # 3 - service not running (unused)
  # 4 - service status unknown :-(
  # 5--199 reserved (5--99 LSB, 100--149 distro, 150--199 appl.)

  # NOTE: checkproc returns LSB compliant status values.
  checkproc $CIYAMD_BIN
  # NOTE: rc_status knows that we called this init script with
  # "status" option and adapts its messages accordingly.
  rc_status -v
  ;;

  *)
   ## If no parameters are given, print which are avaiable.
   echo "Usage: $0 {start|stop|status|restart}"
   exit 1
   ;;

esac

rc_exit

