#! /bin/sh
#
# Installation script for ciyam_server (should generally run as su).
#
echo Installing ciyam_server...
./ciyamd stop
cp ciyam_server /usr/bin
if [ -d /usr/lib64 ]; then
 cp ciyam_base.so /usr/lib64
else
 cp ciyam_base.so /usr/lib
fi
cp ciyamd /etc/init.d
insserv -r /etc/init.d/ciyamd
insserv /etc/init.d/ciyamd
./ciyamd start
