#!/bin/sh
# Copyright (c) 2013-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

# NOTE: Replace with an explicit year leave this empty to derive the year from 'date'.
DATEYEAR=""

if [ ! "$1" = "-skip_check" ]; then
 cat .git/config | grep github.com:ciyam/ciyam.git 2>&1 > /dev/null
 GITCHECK=$?

 if [ "$GITCHECK" != "0" ]; then
  echo "Error: The current directory isn't the CIYAM git repo root directory!"
  exit 1
 fi
fi

if [ "$DATEYEAR" == "" ]; then
 DATEYEAR=`date +%Y`
fi

git ls-files | grep -Ev "\.gz$|\.jpg$|\.png$" | xargs -I{} sed -i "s/Copyright \([0-9]\{4\}\) CIYAM Developers/Copyright (c) \1-${DATEYEAR} CIYAM Developers/" "{}"
git ls-files | grep -Ev "\.gz$|\.jpg$|\.png$" | xargs -I{} sed -i "s/Copyright (c) \([0-9]\{4\}\) CIYAM Developers/Copyright (c) \1-${DATEYEAR} CIYAM Developers/" "{}"
git ls-files | grep -Ev "\.gz$|\.jpg$|\.png$" | xargs -I{} sed -i "s/Copyright \([0-9]\{4\}\)-\([0-9]\{4\}\) CIYAM Developers/Copyright (c) \1-${DATEYEAR} CIYAM Developers/" "{}"
git ls-files | grep -Ev "\.gz$|\.jpg$|\.png$" | xargs -I{} sed -i "s/Copyright (c) \([0-9]\{4\}\)-\([0-9]\{4\}\) CIYAM Developers/Copyright (c) \1-${DATEYEAR} CIYAM Developers/" "{}"

pushd src >/dev/null
./update_package_copyright_year
popd >/dev/null

echo
echo "NOTE: Also need to manually update 'footer.htms' files for generated applications as well as re-generate all HTML documentation files."

exit 0
