load Meta.fcgi.sio
sections
sections -json
attributes user_info
USER_INFO=$OUTPUT
USER_INFO_LINES=@repstr:,/\n:$USER_INFO
USER_CLASS_ID=%USER_INFO_LINES:1%
USER_CLASS_NAME=%USER_INFO_LINES:2%
sections enums.enum
attributes enums.enum.values.*.data,name
attributes -json enums.enum.values.*.data,name
output enums.enum.values
output -json enums.enum.values
output lists.cid=$USER_CLASS_ID
output -json lists.cid=$USER_CLASS_ID
attributes views.*.id,!class=$USER_CLASS_NAME
VIEW_ID=$OUTPUT
output views.id=$VIEW_ID
output -json views.id=$VIEW_ID
available
available -json
attributes enums.*.id,name
attributes lists.*.id,name
attributes lists.*.id,!type=admin
attributes lists.*.id,name,!type=admin|group
attributes views.*.id,name
exit
