.system_variable @test ""
session_variable @errors_only 1
run_script !test "@one=aaa"
run_script !test "@one=aaa,@two=bbb"
system_variable @test
run_script !test "@one=aaa,@two=bbb,@opt1=ccc"
system_variable @test
run_script !test "@one=aaa,@two=bbb,@opt1=ccc,@opt2=ddd"
system_variable @test
run_script !test "@arg1=aaa"
run_script !test "@arg1=aaa,@arg2=bbb"
system_variable @test
run_script !test "@arg1=aaa,@arg2=bbb,@arg3=ccc"
system_variable @test
run_script !test "@arg1=aaa,@arg2=bbb,@arg3=ccc,@arg4=ddd"
system_variable @test
run_script !test "@one=aaa,@arg2=bbb"
system_variable @test
run_script !test "@arg1=aaa,@two=bbb"
system_variable @test
run_script !test "@one=aaa,@arg2=bbb,@opt1=ccc"
system_variable @test
run_script !test "@arg1=aaa,@two=bbb,@arg3=ccc"
system_variable @test
run_script !test "@one=aaa,@arg2=bbb,@opt1=ccc,@arg4=ddd"
system_variable @test
run_script !test "@arg1=aaa,@two=bbb,@arg3=ccc,@opt2=ddd"
system_variable @test
.system_variable @test ""
system_variable @test xxx
system_variable @test
system_variable @test @null
system_variable @test
~touch ~test.sh
run_script test*
~rm -f ~test.txt
run_script test1
run_script test2
wait 250
run_script test3
run_script test4
wait 250
~cat ~test.txt
run_script test2
run_script test1
wait 250
run_script test3
run_script test4
wait 250
~cat ~test.txt
~echo -n "1" >~test.sh
run_script test3
run_script test4
wait 250
~cat ~test.txt
~rm -f ~test.sh
run_script test3
run_script test4
wait 250
~cat ~test.txt
~rm -f ~test.txt
system_variable @trace_filters test1,test2,test3
system_variable @trace_filters
system_variable @trace_filters -test2
system_variable @trace_filters
system_variable @trace_filters -test1
system_variable @trace_filters
system_variable @trace_filters +test1,+test2
system_variable @trace_filters
system_variable @trace_filters ""
system_variable @trace_filters
system_variable @trace_session_ids 1,2,3,4,5
system_variable @trace_session_ids
system_variable @trace_session_ids -
system_variable @trace_session_ids
system_variable @trace_session_ids +
system_variable @trace_session_ids
system_variable @trace_session_ids 2
system_variable @trace_session_ids
system_variable @trace_session_ids +1,+3
system_variable @trace_session_ids
system_variable @trace_session_ids -1,-3
system_variable @trace_session_ids
system_variable @trace_session_ids ""
system_variable @trace_session_ids
system_variable *needed*
system_variable @backup_needed 1
system_variable *needed*
system_variable @restore_needed 1
system_variable *needed*
system_variable @prepare_backup_needed 1
system_variable *needed*
system_variable @complete_restore_needed 1
system_variable *needed*
system_variable @backup_needed 1
system_variable *needed*
system_variable @restore_needed 1
system_variable *needed*
system_variable @prepare_backup_needed 1
system_variable *needed*
system_variable @complete_restore_needed ""
system_variable @prepare_backup_needed 1
system_variable *needed*
system_variable @backup_needed 1
system_variable *needed*
system_variable @restore_needed 1
system_variable *needed*
system_variable @complete_restore_needed 1
system_variable *needed*
system_variable @complete_restore_needed ""
system_variable *needed*
quit
