version
#$MAX_FILE_SIZE
session_list -min
trace_levels
trace_flags -list
strings
string_message total
string_message processed_items @num=999
string_message version_mismatch @found=0.1 @expected=1.0
encrypt -no_ssl -no_salt -pwd_and_data "pwd test_data_to_encrypt"
a=X
b=Y
c=Z
#$a
#$a.
#.$a
#%a%
#%a%.
#.%a%
#$a$b
#$a$b.
#.$a$b
#$a.$b.
#%a%%b%
#.%a%%b%
#%a%%b%.
#%a%.%b%.
#$a$b$c
#$a$b$c.
#.$a$b$c.
#$a.$b.$c.
#%a%%b%%c%
#%a%%b%%c%.
#.%a%%b%%c%.
#%a%.%b%.%c%.
TSX=xxx
TSY=yyy
#$TSX
#$TSY
#$$TSX
#$$TSY
#$TSX$TSY
#$$TSX$TSY
#$TSX$$$TSY
#$$TSX$$TSY
#%TSX%
#%TSY%
#%%TSX
#%%TSY
#%TSX%%TSY%
#%%TSX%TSY%
#%%TSX%%TSY
#%TSX%%%%TSY%
#%%%TSX%%%%TSY%%%
crypto_chain 5 abc
crypto_chain 5 -hind abc
crypto_chain 5 -b64 abc
crypto_chain 5 -b64 -hind abc
crypto_keys test
addr=%OUTPUT:1%
pubkey=%OUTPUT:2%
privkey=%OUTPUT:3%
#addr is: $addr
#pubkey is: $pubkey
#privkey is: $privkey
PWD=abc
#PWD is: $~PWD
#PWD now: $PWD
PWD=abc
#%~PWD%XXX
#%PWD%XXX
TEST=@abc
#$TEST
TEST=@file:modules.lst.default
#$TEST
TEST=@file:~cat modules.lst.default
#$TEST
TEST=abcdefghi
#$TEST
X=@substr:-9:$TEST
#$X
X=@substr:-6:$TEST
#$X
X=@substr:-3:$TEST
#$X
X=@substr:-1:$TEST
#$X
X=@substr:0,-1:$TEST
#$X
X=@substr:0,-2:$TEST
#$X
X=%TEST:0>abc%
#$X
Y=%TEST:0<ghi%
#$Y
Z=%TEST:0>abc<ghi%
#$Z
TEST=abc<def>ghi
#$TEST
X=%TEST:0><<>%
#$X
TEST=abc
NEXT=def
TEST=$TEST\n$NEXT
NEXT=ghi
TEST=$TEST\n$NEXT
#$TEST
HEX=fe
DEC=@hexdec:$HEX
#$DEC
#$HEX
DEC=@$DEC+1
#$DEC
HEX=@dechex:$DEC
#$HEX
DEC=@hexdec:$HEX
DEC=@$DEC+1
#$DEC
HEX=@dechex:$DEC
#$HEX
X=255
HL=@hexlit:$X
#$HL
HB=@hexbig:$X
#$HB
Y=@substr:0,8:$HL
#$Y
Z=@substr:8:$HB
#$Z
Z=@substr:8:$Z
#Empty...$Z
Y=@$X*16
#$Y
Y=@$Y+20
#$Y
Y=@$Y-100
#$Y
Y=@$Y/4000
#$Y
Y=@0<0
#$Y
Y=@0>0
#$Y
Y=@0<=0
#$Y
Y=@0>=0
#$Y
Y=@1<0
#$Y
Y=@1>0
#$Y
Y=@1<=0
#$Y
Y=@1>=0
#$Y
Y=@-1<0
#$Y
Y=@-1>0
#$Y
Y=@-1<=0
#$Y
Y=@-1>=0
#$Y
VAL=0
MOD=@$VAL#10
#$MOD
VAL=1
MOD=@$VAL#10
#$MOD
VAL=2
MOD=@$VAL#10
#$MOD
VAL=8
MOD=@$VAL#10
#$MOD
VAL=9
MOD=@$VAL#10
#$MOD
VAL=10
MOD=@$VAL#10
#$MOD
VAL=11
MOD=@$VAL#10
#$MOD
VAL=12
MOD=@$VAL#10
#$MOD
VAL=98
MOD=@$VAL#10
#$MOD
VAL=99
MOD=@$VAL#10
#$MOD
VAL=100
MOD=@$VAL#10
#$MOD
VAL=110
MOD=@$VAL#10
#$MOD
VAL=111
MOD=@$VAL#10
#$MOD
VAL=112
MOD=@$VAL#10
#$MOD
NUM_A=123
NUM_B=123
#RESULT=@$NUM_A=$NUM_B
RESULT=@$NUM_A=$NUM_B
#$RESULT
#RESULT=@$NUM_A<$NUM_B
RESULT=@$NUM_A<$NUM_B
#$RESULT
#RESULT=@$NUM_A<=$NUM_B
RESULT=@$NUM_A<=$NUM_B
#$RESULT
#RESULT=@$NUM_A>$NUM_B
RESULT=@$NUM_A>$NUM_B
#$RESULT
#RESULT=@$NUM_A>=$NUM_B
RESULT=@$NUM_A>=$NUM_B
#$RESULT
NUM_A=122
NUM_B=123
#RESULT=@$NUM_A=$NUM_B
RESULT=@$NUM_A=$NUM_B
#$RESULT
#RESULT=@$NUM_A<$NUM_B
RESULT=@$NUM_A<$NUM_B
#$RESULT
#RESULT=@$NUM_A<=$NUM_B
RESULT=@$NUM_A<=$NUM_B
#$RESULT
#RESULT=@$NUM_A>$NUM_B
RESULT=@$NUM_A>$NUM_B
#$RESULT
#RESULT=@$NUM_A>=$NUM_B
RESULT=@$NUM_A>=$NUM_B
#$RESULT
NUM_A=123
NUM_B=122
#RESULT=@$NUM_A=$NUM_B
RESULT=@$NUM_A=$NUM_B
#$RESULT
#RESULT=@$NUM_A<$NUM_B
RESULT=@$NUM_A<$NUM_B
#$RESULT
#RESULT=@$NUM_A<=$NUM_B
RESULT=@$NUM_A<=$NUM_B
#$RESULT
#RESULT=@$NUM_A>$NUM_B
RESULT=@$NUM_A>$NUM_B
#$RESULT
#RESULT=@$NUM_A>=$NUM_B
RESULT=@$NUM_A>=$NUM_B
#$RESULT
@ifdef $Y
#ifdef true
@else
#ifdef false
@endif
@ifndef $Y
#ifndef true
@else
#ifndef false
@endif
Y=
@ifdef $Y
#ifdef true
@else
#ifdef false
@endif
@ifndef $Y
#ifndef true
@else
#ifndef false
@endif
ASC=1234567890
#$ASC
HEX=@aschex:$ASC
#$HEX
ASC=@hexasc:$HEX
#$ASC
HASH=@sha256:$ASC
#$HASH
X=x
Y=y
@ifeq $X $Y
#@ifeq $X $Y true
@else
#@ifeq $X $Y false
@endif
@ifneq $X $Y
#@ifneq $X $Y true
@else
#@ifneq $X $Y false
@endif
X=$Y
@ifeq $X $Y
#@ifeq $X $Y true
@else
#@ifeq $X $Y false
@endif
@ifneq $X $Y
#@ifneq $X $Y true
@else
#@ifneq $X $Y false
@endif
X=xxyyzz
#$X
X=@repstr:zz/xx:$X
#$X
X=ab/cd/ef
#$X
X=@repstr:\//\::$X
#$X
X=@repstr:\:/\/:$X
#$X
!-0
!
#a
#b
#c
#d
#e
!
!-1
!
!!-
!
!1
!!
!2
!1#2
#e
!2#2
!2#0
#f
#g
!
!-#3
!
!0
#e
#f
#g
!
!-2#3
!
#h
#i
#j
!
!-3#0
!
!-0
;
<test_console.cin
;
<channel_identity.cin abc123def aaa121aaa
#IDENT: $IDENT
#OTHER: $OTHER
#COMBINED: $COMBINED
#REVERSED: $REVERSED
#CIYAM_FISSILE: $CIYAM_FISSILE
;
@retain COMBINED,REVERSED
<channel_identity.cin abc123def aaa121aaa
#IDENT: $IDENT
#OTHER: $OTHER
#COMBINED: $COMBINED
#REVERSED: $REVERSED
#CIYAM_FISSILE: $CIYAM_FISSILE
;
@retain *
<channel_identity.cin abc123def aaa121aaa
#IDENT: $IDENT
#OTHER: $OTHER
#COMBINED: $COMBINED
#REVERSED: $REVERSED
#CIYAM_FISSILE: $CIYAM_FISSILE
;
PATHS=@paths:..:^.git*,^src/tmp*,^src/haru*,^src/.files*
#$PATHS
;
#[test*.jpg]
FILES=@files::test*.jpg
#$FILES
;
#[test?.jpg]
FILES=@files::test?.jpg
#$FILES
;
#[test*.jpg,^test.jpg]
FILES=@files::test*.jpg,^test.jpg
#$FILES
;
#[test1.jpg,test2.jpg]
FILES=@files::test1.jpg,test2.jpg
#$FILES
;
#[test.jpg]
FILES=@files::test.jpg
#$FILES
;
encode -text a
decode -text $OUTPUT
encode -text ab
decode -text $OUTPUT
encode -text abc
decode -text $OUTPUT
encode -text abcd
decode -text $OUTPUT
encode -text abcde
decode -text $OUTPUT
encode -text abcdef
decode -text $OUTPUT
encode -text abcdefg
decode -text $OUTPUT
encode -text abcdefg
decode -text $OUTPUT
encode -text abcdefgh
decode -text $OUTPUT
;
encode -url -text a
decode -url -text $OUTPUT
encode -url -text ab
decode -url -text $OUTPUT
encode -url -text abc
decode -url -text $OUTPUT
encode -url -text abcd
decode -url -text $OUTPUT
encode -url -text abcde
decode -url -text $OUTPUT
encode -url -text abcdef
decode -url -text $OUTPUT
encode -url -text abcdefg
decode -url -text $OUTPUT
encode -url -text abcdefg
decode -url -text $OUTPUT
encode -url -text abcdefgh
decode -url -text $OUTPUT
;
=crypto_hash hello
crypto_hash hello
encode $OUTPUT
decode $OUTPUT
;
crypto_hash hello
encode -url $OUTPUT
decode -url $OUTPUT
;
=crypto_hash -512 hello
crypto_hash -512 hello
encode $OUTPUT
decode $OUTPUT
;
crypto_hash -512 hello
encode -url $OUTPUT
decode -url $OUTPUT
;
crypto_hash -x=0 hello
crypto_hash -x=1 hello
crypto_hash -x=2 hello
crypto_hash -x=3 hello
crypto_hash -x=4 hello
crypto_hash -x=5 hello
crypto_hash -x=6 hello
crypto_hash -x=7 hello
crypto_hash -x=8 hello
crypto_hash -x=9 hello
crypto_hash -x=9 hello -s=0
crypto_hash -x=9 hello -s=1
crypto_hash -x=9 hello -s=2
crypto_hash -x=9 hello -s=3
crypto_hash -x=9 hello -s=4
crypto_hash -x=9 hello -s=5
;
crypto_lamport xxx xxx
~cp modules.lst.default xxx.src
crypto_lamport -sign xxx
crypto_lamport -verify xxx
file_put xxx.key xxx.key
file_put xxx.pub xxx.pub
file_put xxx.sig xxx.sig
crypto_lamport -verify xxx.pub:xxx.sig
crypto_lamport -verify xxx.pub:xxx.key
file_kill xxx.key
file_kill xxx.pub
file_kill xxx.sig
~rm xxx.key xxx.pub xxx.sig xxx.src
;
regex "^[@]?[a-b][a-b]+$$" "@"
regex "^[@]?[a-b][a-b]+$$" "a"
regex "^[@]?[a-b][a-b]+$$" "@@"
regex "^[@]?[a-b][a-b]+$$" "@a"
regex "^[@]?[a-b][a-b]+$$" "@b"
regex "^[@]?[a-b][a-b]+$$" "aa"
regex "^[@]?[a-b][a-b]+$$" "ab"
regex "^[@]?[a-b][a-b]+$$" "ba"
regex "^[@]?[a-b][a-b]+$$" "bb"
regex "^[@]?[a-b][a-b]+$$" "a@"
regex "^[@]?[a-b][a-b]+$$" "b@"
regex "^[@]?[a-b][a-b]+$$" "@aa"
regex "^[@]?[a-b][a-b]+$$" "@ab"
regex "^[@]?[a-b][a-b]+$$" "@ba"
regex "^[@]?[a-b][a-b]+$$" "@bb"
regex "^[@]?[a-b][a-b]+$$" "@@a"
regex "^[@]?[a-b][a-b]+$$" "@@b"
regex "^[@]?[a-b][a-b]+$$" "@a@"
regex "^[@]?[a-b][a-b]+$$" "@b@"
regex "^[@]?[a-b][a-b]+$$" "aaa"
regex "^[@]?[a-b][a-b]+$$" "aab"
regex "^[@]?[a-b][a-b]+$$" "aba"
regex "^[@]?[a-b][a-b]+$$" "abb"
regex "^[@]?[a-b][a-b]+$$" "baa"
regex "^[@]?[a-b][a-b]+$$" "bab"
regex "^[@]?[a-b][a-b]+$$" "bba"
regex "^[@]?[a-b][a-b]+$$" "bbb"
regex "^[@]?[a-b][a-b]+$$" "@aaa"
regex "^[@]?[a-b][a-b]+$$" "@aab"
regex "^[@]?[a-b][a-b]+$$" "@aba"
regex "^[@]?[a-b][a-b]+$$" "@abb"
regex "^[@]?[a-b][a-b]+$$" "@baa"
regex "^[@]?[a-b][a-b]+$$" "@bab"
regex "^[@]?[a-b][a-b]+$$" "@bba"
regex "^[@]?[a-b][a-b]+$$" "@bbb"
regex "^[@]?[a-b][a-b]+$$" "@aa@"
regex "^[@]?[a-b][a-b]+$$" "@aa@"
regex "^[@]?[a-b][a-b]+$$" "@ab@"
regex "^[@]?[a-b][a-b]+$$" "@ab@"
regex "^[@]?[a-b][a-b]+$$" "@ba@"
regex "^[@]?[a-b][a-b]+$$" "@ba@"
regex "^[@]?[a-b][a-b]+$$" "@bb@"
regex "^[@]?[a-b][a-b]+$$" "@bb@"
;
regex "abc(def)?ghi" abcghi
regex "abc(def)?ghi" abcdefghi
regex "abc(def)?ghi" abcghijkl
regex -refs "abc(def)?ghi" abcghijkl
regex -input "abc(def)?ghi" abcghijkl
regex -matched "abc(def)?ghi" abcghijkl
regex "bc\\\.(.*)\\\." bc.abc123def.99.blk
regex "bc\\\.(.*)\\\." bc.abc123def.zenith
regex "^([a-z]{1}[a-z0-9]{0,8}[a-z]{1})" abc123def
regex "([a-z]{1}[a-z0-9]{0,8}[a-z]{1})$$" abc123def
regex "^([a-z]{1}[a-z0-9]{0,8}[a-z]{1})$$" abc123def
regex -matched "([a-b]*[0-9]{3,5}[a-z]{1})$$" abcdef1234g
regex -matched "([a-f]+[0-9]{3,5}[a-z]{1})$$" abcdef1234g
;
regex -chain "^[a-z][-a-z0-9]{2,29}$$&&.*[^-]$$&!^.*--.*$$" abc
regex -chain "^[a-z][-a-z0-9]{2,29}$$&&.*[^-]$$&!^.*--.*$$" a-c
regex -chain "^[a-z][-a-z0-9]{2,29}$$&&.*[^-]$$&!^.*--.*$$" -b-
regex -chain "^[a-z][-a-z0-9]{2,29}$$&&.*[^-]$$&!^.*--.*$$" ---
regex -chain "^[a-z][-a-z0-9]{2,29}$$&&.*[^-]$$&!^.*--.*$$" a--
regex -chain "^[a-z][-a-z0-9]{2,29}$$&&.*[^-]$$&!^.*--.*$$" --c
regex -chain "^[a-z][-a-z0-9]{2,29}$$&&.*[^-]$$&!^.*--.*$$" abcd
regex -chain "^[a-z][-a-z0-9]{2,29}$$&&.*[^-]$$&!^.*--.*$$" -bcd
regex -chain "^[a-z][-a-z0-9]{2,29}$$&&.*[^-]$$&!^.*--.*$$" a-cd
regex -chain "^[a-z][-a-z0-9]{2,29}$$&&.*[^-]$$&!^.*--.*$$" ab-d
regex -chain "^[a-z][-a-z0-9]{2,29}$$&&.*[^-]$$&!^.*--.*$$" abc-
regex -chain "^[a-z][-a-z0-9]{2,29}$$&&.*[^-]$$&!^.*--.*$$" ab--
regex -chain "^[a-z][-a-z0-9]{2,29}$$&&.*[^-]$$&!^.*--.*$$" --cd
regex -chain "^[a-z][-a-z0-9]{2,29}$$&&.*[^-]$$&!^.*--.*$$" abcde
regex -chain "^[a-z][-a-z0-9]{2,29}$$&&.*[^-]$$&!^.*--.*$$" a-c-e
regex -chain "^[a-z][-a-z0-9]{2,29}$$&&.*[^-]$$&!^.*--.*$$" a---e
;
regex "([a-z]+)" abc-def
regex "([a-z]+)([-_.][a-z]+)" abc-def
regex "([a-z]+)([-_.][a-z]+)" abc_def
regex "([a-z]+)([-_.][a-z]+)" abc.def
regex "([a-z]+)([-_.][a-z]+)" abc--def
regex "([a-z]+)([-_.][a-z]+)" abc__def
regex "([a-z]+)([-_.][a-z]+)" abc..def
regex "([a-z]+)([-_.][a-z]+)" abc-_def
regex "([a-z]+)([-_.][a-z]+)" abc-.def
regex "([a-z]+)([-_.][a-z]+)" abc_-def
regex "([a-z]+)([-_.][a-z]+)" abc_.def
regex "([a-z]+)([-_.][a-z]+)" abc.-def
regex "([a-z]+)([-_.][a-z]+)" abc._def
regex "([a-z]+)([-_.][a-z]+)([-_.][a-z]+)" abc-def-ghi
;
regex @peerchain_identity 012343210
regex @peerchain_identity abcdedbca
regex @peerchain_identity abcd01234
regex @peerchain_identity abcdefg01
regex @peerchain_identity 0123456789
regex @peerchain_identity 1234567890
;
soundex no
soundex now
soundex our
soundex hour
soundex know
soundex ours
soundex hours
soundex nemonics
soundex mnemonics
soundex sycolagee
soundex psychology
;
soundex -skip no
soundex -skip now
soundex -skip hour
soundex -skip know
soundex -skip ours
soundex -skip hours
soundex -skip nemonics
soundex -skip mnemonics
soundex -skip sycolagee
soundex -skip psychology
;
session_variable test (okay)
session_variable test
session_variable test @increment
session_variable test
session_variable test @increment
session_variable test
session_variable test @increment
session_variable test
session_variable test @decrement
session_variable test
session_variable test @decrement
session_variable test
session_variable test @decrement
session_variable test
session_variable test xxx
session_variable test
session_variable test @null
session_variable test
session_variable @set aaa
session_variable @set aaa
session_variable @set bbb
session_variable @set bbb
session_variable @set ccc
session_variable @set ccc
session_variable @set aaa
session_variable @set bbb
session_variable @set ccc
session_variable @set
session_variable @set ?a
session_variable @set ?aa
session_variable @set ?aaa
session_variable @set ?aaa,b
session_variable @set ?aaa,c
session_variable @set ?aaa,bb
session_variable @set ?aaa,cc
session_variable @set ?aaa,bbb
session_variable @set ?aaa,ccc
session_variable @set ?aaa,bbb,c
session_variable @set ?aaa,bbb,d
session_variable @set ?aaa,bbb,cc
session_variable @set ?aaa,bbb,dd
session_variable @set ?aaa,bbb,ccc
session_variable @set ?aaa,bbb,ddd
session_variable @deque @set
session_variable @deque
session_variable @deque @set
session_variable @deque
session_variable @deque "push_back yyy"
session_variable @deque "push_front xxx"
session_variable @deque
session_variable @deque pop_back
session_variable @deque pop_front
session_variable @deque
session_variable @deque "push_front eee"
session_variable @deque "push_front ddd"
session_variable @deque
session_variable @set @deque
session_variable @set
;
session_variable @deque ""
session_variable @deque "take 1"
session_variable @deque "push_back aaa"
session_variable @deque "push_back bbb"
session_variable @deque "push_back ccc"
session_variable @deque "push_back ddd"
session_variable @deque "push_back eee"
session_variable @deque "push_back fff"
session_variable @deque "push_back ggg"
session_variable @deque "push_back hhh"
session_variable @deque
session_variable @deque "take 0"
session_variable @deque
session_variable @deque "take 2"
session_variable @deque
session_variable @deque "take -3"
session_variable @deque
session_variable @deque "take -2"
session_variable @deque
;
session_variable @queue_test abc
session_variable @queue_test def
session_variable @queue_test ghi
session_variable @queue_test
session_variable @queue_test
session_variable @queue_test
session_variable @queue_test
;
session_variable @mapped_test:abc xxx
session_variable @mapped_test:def yyy
session_variable @mapped_test:ghi zzz
session_variable @mapped_test:abc
session_variable @mapped_test:def
session_variable @mapped_test:ghi
session_variable @mapped_test:abc 111
session_variable @mapped_test:def 222
session_variable @mapped_test:ghi 333
session_variable @mapped_test
session_variable @mapped_test:abc
session_variable @mapped_test:def
session_variable @mapped_test:ghi
session_variable @mapped_test:abc ""
session_variable @mapped_test:abc
session_variable @mapped_test:def
session_variable @mapped_test:ghi
session_variable @mapped_test
session_variable @mapped_test:def ""
session_variable @mapped_test:abc
session_variable @mapped_test:def
session_variable @mapped_test:ghi
session_variable @mapped_test
session_variable @mapped_test ""
session_variable @mapped_test:abc
session_variable @mapped_test:def
session_variable @mapped_test:ghi
;
<test_args.cin XXX
<test_args.cin XXX YYY
<test_args.cin XXX YYY ZZZ
<test_args.cin XXX "" ZZZ
<test_args.cin "" "" ZZZ
;
_#Test $0...
_<test_args.cin $1 $2 $3
;
utc_to_local AEST "2013-10-05 15:00"
utc_to_local AEST+ "2013-10-05 15:00"
utc_from_local AEST "2013-10-06 01:00"
utc_to_local AEST "2013-10-06 16:00"
utc_to_local AEST+ "2013-10-06 16:00"
utc_from_local AEST "2013-10-07 03:00"
utc_from_local AEDT "2013-10-07 03:00"
utc_to_local AEST "2014-04-05 15:00"
utc_to_local AEST+ "2014-04-05 15:00"
utc_from_local AEST "2014-04-06 02:00"
utc_from_local AEDT "2014-04-06 02:00"
utc_to_local AEST "2014-04-05 16:00"
utc_to_local AEST+ "2014-04-05 16:00"
utc_from_local AEST "2014-04-06 02:00"
utc_from_unix_time 0
utc_to_unix_time "1970-01-01 00:00:00"
utc_from_unix_time 631152000
utc_to_unix_time "1990-01-01 00:00:00"
utc_from_unix_time 946684800
utc_to_unix_time "2000-01-01 00:00:00"
utc_from_unix_time 1000000000
utc_to_unix_time "2001-09-09 01:46:40"
utc_from_unix_time 1320195610
utc_to_unix_time "2011-11-02 01:00:10"
.quit
