storage_init ciyam
session_variable @dump_minimal 1
storage_bulk_start read
storage_bulk_start read
storage_bulk_start write
storage_bulk_finish
storage_bulk_start write
storage_bulk_start write
storage_bulk_start read
storage_bulk_finish
storage_lock_create view test
storage_lock_create view test
storage_lock_create view test
storage_dump_locks
storage_lock_modify 2 review
storage_lock_modify 3 review
storage_dump_locks
storage_lock_modify 3 obtain
storage_dump_locks
storage_lock_modify 2 obtain
storage_lock_modify 3 update
storage_lock_modify 2 view
storage_lock_modify 3 update
storage_dump_locks
storage_lock_modify 2 review
storage_lock_modify 3 obtain
storage_dump_locks
storage_lock_modify 2 review
storage_lock_modify 3 destroy
storage_lock_modify 2 view
storage_dump_locks
storage_lock_modify 3 destroy
storage_lock_modify 2 review
storage_dump_locks
storage_lock_modify 3 obtain
storage_lock_create review test abc
storage_dump_locks
storage_lock_modify 3 update
storage_lock_modify 4 view
storage_lock_modify 3 update
storage_dump_locks
storage_lock_modify 4 review
storage_lock_create review test def
storage_lock_modify 3 obtain
storage_lock_create review test def
storage_dump_locks
storage_lock_modify 4 review
storage_lock_modify 4 update
storage_lock_modify 3 view
storage_dump_locks
storage_lock_modify 4 update
storage_lock_modify 5 update
storage_dump_locks
storage_lock_modify 3 obtain
storage_lock_modify 4 review
storage_lock_modify 3 obtain
storage_lock_modify 5 review
storage_dump_locks
storage_lock_modify 3 obtain
storage_dump_locks
storage_lock_modify 3 update
storage_lock_remove 5
storage_dump_locks
storage_lock_modify 3 update
storage_lock_remove 4
storage_lock_modify 3 update
storage_dump_locks
storage_lock_modify 2 update
storage_lock_remove 3
storage_lock_modify 2 update
storage_dump_locks
storage_lock_modify 1 obtain
storage_lock_modify 2 review
storage_lock_modify 1 obtain
storage_dump_locks
storage_lock_remove 1
storage_lock_modify 2 destroy
storage_dump_locks
storage_lock_modify 2 create
storage_dump_locks
storage_lock_create link test
storage_lock_modify 2 destroy
storage_lock_create link test
storage_lock_modify 2 update
storage_lock_create link test
storage_lock_create link test
storage_lock_modify 2 destroy
storage_lock_remove 7
storage_lock_modify 2 destroy
storage_lock_remove 6
storage_lock_modify 2 destroy
storage_dump_locks
storage_lock_modify 2 view
storage_dump_locks
storage_lock_remove 2
storage_variable >test1 aaa
storage_variable test2 bbb
storage_variable >test3 ccc
storage_variable test4 ddd
storage_variable >test5 eee
storage_variable >
storage_variable <
storage_variable test1 xxx
storage_variable >
storage_variable <
storage_variable test3 yyy
storage_variable >
storage_variable <
storage_variable test5 zzz
storage_variable >
storage_variable <
storage_variable >test?
storage_variable >
storage_variable <
storage_variable *
storage_variable test1 aaa
storage_variable test3 ccc
storage_variable test5 eee
storage_variable *
storage_variable <
storage_variable >test?
storage_variable >
storage_variable <
storage_variable *
session_variable @attached_file_path .
object_create 100 100100
object_op_update 1 guest
object_execute 1 get Workgroup
object_execute 1 set "Workgroup crap"
object_execute 1 set "Workgroup ?crap"
object_execute 1 get Workgroup
object_op_cancel 1
object_destroy 1
pf Meta Enum_Item "" Label,@order,@level,Enum,Enum.Name,Enum.@group,@owner
pc guest 20120102 100 105100 guest_model "105101=Sample,300500=guests,105102=0.1,105103=2012,105104=M001,105112=0,105118=0"
pf 100 105100 guest_model "105101,105102,105103,105104,105105,105106,105107,105108,105109,105110,105111,105112,105113,105114,105118"
pc guest 20120102 100 136100 guest_standard "136101=Standard,136107=Standard,302810=Standard,302800=guest_model"
pe guest 20120102 100 136100 "-v=@async=false,@message=Installing Standard Package..." guest_standard =1.0 -136410
pc guest 20120102 100 136100 guest_user "136101=User,136107=User,302810=User,302800=guest_model"
pe guest 20120102 100 136100 "-v=@async=false,@message=Installing User Package..." guest_user =1.0 -136410
pf 100 106100 "106104 " 106101,106102,106104 -min
pf 100 107100 "107110 " 107101,107110 -min
pf 100 103100 "103104 " 103101,103104 -min
pf 100 102100 "102111 " 102101,102111 -min
.quit
