cd
branch objects
cd abc
folders
folder_move aaa bbb
folders
folder_move bbb aaa
folders
folder_remove def
folder_remove -r def
cd /
branch folders
folder_remove abc
folder_remove -r abc
branch folders
folder_remove ghi
folder_remove -r ghi
branch folders
branch objects
dump
folder_add xxx
folder_add xxx/.yyy
folder_add xxx/.yyy/zzz
branch objects
branch -f objects
branch -f -u objects
folder_remove xxx
folder_remove -r xxx
branch folders
branch objects
dump
exit
