session_variable @progress_total 100000
session_variable @progress_count 0
session_variable @progress_value
session_variable @progress_count 1
session_variable @progress_value
session_variable @progress_count 5
session_variable @progress_value
session_variable @progress_count 10
session_variable @progress_value
session_variable @progress_count 15
session_variable @progress_value
session_variable @progress_count 50
session_variable @progress_value
session_variable @progress_count 100
session_variable @progress_value
session_variable @progress_count 200
session_variable @progress_value
session_variable @progress_count 250
session_variable @progress_value
session_variable @progress_count 275
session_variable @progress_value
session_variable @progress_count 276
session_variable @progress_value
session_variable @progress_count 277
session_variable @progress_value
session_variable @progress_count 280
session_variable @progress_value
session_variable @progress_count 290
session_variable @progress_value
session_variable @progress_count 300
session_variable @progress_value
session_variable @progress_count 350
session_variable @progress_value
session_variable @progress_count 400
session_variable @progress_value
session_variable @progress_count 500
session_variable @progress_value
session_variable @progress_count 1000
session_variable @progress_value
session_variable @progress_count 2000
session_variable @progress_value
session_variable @progress_count 3000
session_variable @progress_value
session_variable @progress_count 5000
session_variable @progress_value
session_variable @progress_count 99000
session_variable @progress_value
session_variable @progress_count 99010
session_variable @progress_value
session_variable @progress_count 99020
session_variable @progress_value
session_variable @progress_count 99025
session_variable @progress_value
session_variable @progress_count 99050
session_variable @progress_value
session_variable @progress_count 99100
session_variable @progress_value
session_variable @progress_count 99200
session_variable @progress_value
session_variable @progress_count 99500
session_variable @progress_value
session_variable @progress_count 99900
session_variable @progress_value
session_variable @progress_count 99990
session_variable @progress_value
session_variable @progress_count 99999
session_variable @progress_value
session_variable @progress_count 100000
session_variable @progress_value
system_variable @queue_test abc
system_variable @queue_test def
system_variable @queue_test ghi
system_variable @queue_test
system_variable @queue_test
system_variable @queue_test
system_variable @queue_test
session_variable @queue_test abc
session_variable @queue_test def
session_variable @queue_test ghi
session_variable @queue_test
session_variable @queue_test
session_variable @queue_test
session_variable @queue_test
system_variable @sys_var_prefix test
system_variable >test_a aaa
system_variable >test_b bbb
system_variable >test_c ccc
system_variable ?test_a
system_variable !test_a
system_variable ?test_x
system_variable !test_x
system_variable ?test_a|?test_b
system_variable ?test_a|?test_x
system_variable ?test_a&?test_b
system_variable ?test_a&?test_x
system_variable ?test_a&!test_x
system_variable !test_a|!test_b
system_variable !test_a|!test_x
system_variable !test_a&!test_x
system_variable *
system_variable **
system_variable >
system_variable <
system_variable test_a ddd
system_variable *
system_variable **
system_variable >
system_variable <
system_variable test_b eee
system_variable *
system_variable >
system_variable <
system_variable test_c fff
system_variable *
system_variable **
system_variable >
system_variable <
system_variable <test_a
system_variable *
system_variable >
system_variable <
system_variable <*
system_variable *
system_variable >
system_variable <
system_variable test_a ""
system_variable test_b ""
system_variable test_c ""
system_variable *
system_variable >
system_variable <
system_variable >*
system_variable *
system_variable >
system_variable <
system_variable @sys_var_prefix ""
system_variable test_a aaa
system_variable "test a" aaa
system_variable test_b bbb
system_variable "test b" bbb
system_variable test_c ccc
system_variable "test c" ccc
system_variable test*
system_variable "\"abc\"" abc
system_variable xxx yyy ""
system_variable xxx
system_variable xxx zzz ""
system_variable xxx
system_variable xxx zzz yyy
system_variable xxx
system_variable xxx "" yyy
system_variable xxx
system_variable xxx "" zzz
system_variable xxx
session_restrict abc "session_variable"
system_variable xxx
session_variable xxx
session_restrict def ""
system_variable xxx
session_variable xxx
session_restrict abc ""
session_variable xxx
system_variable xxx
.quit
