file_raw -text blob "Hello World!"
file_raw -text blob "This is a test."
file_raw -text list "2ccdb4c72e6c263e1dc3e5c6617bad479d267546ced55f88d6b6e4527d2e8da8 hello\n90a1a46903f42ddf0386a9c12fd67a6c109285bb8b3117ee83ed222fd0040ad3 test" root
file_raw -text blob "at 0..."
file_raw -text blob "at 1..."
file_raw -text list "fb9677b46fbcd4bb532d10d305a5d8ebe90c9f252d655747a406ba1e7a859e25 0\n055ab3dc27be99b17779d4e5087c559f0f8743d5ac8575c5e340936b6d34ab08 1"
file_raw -text list "c158947de2088bcacd73ee2d6c5ca30200f1b4d47d409ea015c13777427a9eb1 first\nf0e0bbbf3321c7e483e3f7b4072e87791e1ec3cb74c3d4ac0db4faa765f12e32 second" root
file_hash root
file_hash !35ddd
file_hash !f*
file_info -content root
file_info -recurse -d=1 root
file_info -recurse -d=1 -p=first root
file_info -recurse -d=1 -p=^first root
file_info -recurse -d=2 root
file_info -recurse -d=2 -p=first: root
file_info -recurse -d=2 -p=^first: root
file_info -recurse -d=0 root
file_info -recurse -d=-1 root
file_info -recurse -d=-2 root
file_info -total_items root
file_info -total_items root:!
file_info -total_items root:xxx
file_info -total_items root:c158947de2088bcacd73ee2d6c5ca30200f1b4d47d409ea015c13777427a9eb1
file_info -total_items root:2ccdb4c72e6c263e1dc3e5c6617bad479d267546ced55f88d6b6e4527d2e8da8
file_info -total_items root:90a1a46903f42ddf0386a9c12fd67a6c109285bb8b3117ee83ed222fd0040ad3
file_info -total_items root:f0e0bbbf3321c7e483e3f7b4072e87791e1ec3cb74c3d4ac0db4faa765f12e32
file_info -total_items root:fb9677b46fbcd4bb532d10d305a5d8ebe90c9f252d655747a406ba1e7a859e25
file_info -total_items root:055ab3dc27be99b17779d4e5087c559f0f8743d5ac8575c5e340936b6d34ab08
file_tag fb9677b46fbcd4bb532d10d305a5d8ebe90c9f252d655747a406ba1e7a859e25 test0
file_tag 055ab3dc27be99b17779d4e5087c559f0f8743d5ac8575c5e340936b6d34ab08 test1
file_raw list test0,test1 testx
file_info -content testx
file_tags test*
file_tags -i=te*0,te*1
file_tags -i=test* -x=*x
file_tags -i=test* -x=*0,*x
file_kill testx
file_tags test*
file_tag -remove test0,test1
file_tags test*
file_kill -recurse root
#~mkdir test1
~mkdir test1
~touch test1/xxx
~touch test1/yyy
TEST=@file:~./diff -q test1/xxx test1/yyy
#$SYSTEM_RETVAL
#$TEST
~rm test1/yyy
TEST=@file:~./diff -q test1/xxx test1/yyy
#$SYSTEM_RETVAL
#$TEST
notifier -start test1/xxx
system_variable *test1*
#~touch test1/xxx
~touch test1/xxx
.wait 100
system_variable *test1*
#~rm test1/xxx
~rm test1/xxx
.wait 150
system_variable *test1*
notifier -start test1
system_variable *test1*
#~touch test1/x
~touch test1/x
#~touch test1/y
~touch test1/y
#~touch test1/z
~touch test1/z
.wait 100
system_variable *test1*
#~touch test1/x
~touch test1/x
#~touch test1/y
~touch test1/y
#~touch test1/z
~touch test1/z
.wait 100
system_variable *test1*
#~rm test1/x
~rm test1/x
#~rm test1/y
~rm test1/y
#~rm test1/z
~rm test1/z
.wait 100
system_variable *test1*
#~touch test1/x
~touch test1/x
.wait 100
system_variable *test1*
#~mv test1/x test1/xx
~mv test1/x test1/xx
.wait 100
system_variable *test1*
#~mv test1/xx test1/xxx
~mv test1/xx test1/xxx
.wait 100
system_variable *test1*
#~mv test1/xxx test1/x
~mv test1/xxx test1/x
.wait 100
system_variable *test1*
~rm test1/x
notifier -finish test1
system_variable *test1*
#~mkdir test1/xxx
~mkdir test1/xxx
notifier -start test1/xxx
system_variable *test1*
#~rmdir test1/xxx
~rmdir test1/xxx
.wait 150
system_variable *test1*
notifier -start test1
#~mkdir test1/xxx
~mkdir test1/xxx
#~mkdir test1/zzz
~mkdir test1/zzz
.wait 100
system_variable *test1*
#~mv test1/zzz test1/yyy
~mv test1/zzz test1/yyy
.wait 100
system_variable *test1*
#~mkdir test1/yyy/zzz
~mkdir test1/yyy/zzz
.wait 100
system_variable *test1*
#~touch test1/yyy/zzz/abc
~touch test1/yyy/zzz/abc
.wait 100
system_variable *test1*
#~mv test1/yyy test1/xxx
~mv test1/yyy test1/xxx
.wait 100
system_variable *test1*
#~touch test1/xxx/yyy/zzz/def
~touch test1/xxx/yyy/zzz/def
.wait 100
system_variable *test1*
notifier -finish test1
#~rm -r test1/xxx
~rm -r test1/xxx
#~touch test1/x
~touch test1/x
notifier -start test1
system_variable *test1*
#~mv test1/x test1/y
~mv test1/x test1/y
.wait 100
system_variable *test1*
#~touch test1/z
~touch test1/z
#~mv test1/z test1/y
~mv test1/z test1/y
.wait 100
system_variable *test1*
#~rm test1/y
~rm test1/y
.wait 100
system_variable *test1*
notifier -finish test1
#~mkdir test1/xxx
~mkdir test1/xxx
#~touch test1/xxx/111
~touch test1/xxx/111
#~touch test1/xxx/222
~touch test1/xxx/222
notifier -start test1
system_variable *test1*
#~mv test1/xxx test1/yyy
~mv test1/xxx test1/yyy
.wait 100
system_variable *test1*
notifier -finish test1
#~rm -r test1/yyy
~rm -r test1/yyy
#~mkdir test1/xxx
~mkdir test1/xxx
#~touch test1/xxx/111 test1/xxx/222
~touch test1/xxx/111 test1/xxx/222
notifier -start test1/xxx
system_variable *test1*
#~touch test1/xxx/333
~touch test1/xxx/333
#~mv test1/xxx/111 test1/xxx/222 test1
~mv test1/xxx/111 test1/xxx/222 test1
.wait 100
system_variable *test1*
#~rm test1/xxx/333
~rm test1/xxx/333
.wait 100
system_variable *test1*
notifier -finish test1/xxx
#~rm test1/111 test1/222
~rm test1/111 test1/222
#~touch test1/xxx/111
~touch test1/xxx/111
notifier -start test1/xxx
system_variable *test1/xxx*
system_variable test1/xxx/111 "[000001]++none"
#~touch test1/xxx/111
~touch test1/xxx/111
.wait 100
system_variable *test1/xxx*
#~mv test1/xxx/111 test1/xxx/222
~mv test1/xxx/111 test1/xxx/222
.wait 100
system_variable *test1/xxx*
#~rm test1/xxx/222
~rm test1/xxx/222
.wait 100
system_variable *test1/xxx*
notifier -finish test1/xxx
#~touch test1/xxx/111
~touch test1/xxx/111
notifier -start test1/xxx
system_variable *test1/xxx*
#~mv test1/xxx/111 test1/xxx/222
~mv test1/xxx/111 test1/xxx/222
.wait 100
system_variable *test1/xxx*
#~touch test1/xxx/111
~touch test1/xxx/111
.wait 100
system_variable *test1/xxx*
#~rm test1/xxx/222
~rm test1/xxx/222
.wait 100
system_variable *test1/xxx*
#~rm test1/xxx/111
~rm test1/xxx/111
.wait 100
system_variable *test1/xxx*
notifier -finish test1/xxx
#~touch test1/xxx/111
~touch test1/xxx/111
notifier -start test1/xxx
system_variable *test1/xxx*
notifier -suspend test1/xxx
#~touch test1/xxx/111
~touch test1/xxx/111
.wait 100
system_variable *test1/xxx*
notifier -unsuspend test1/xxx
#~touch test1/xxx/111
~touch test1/xxx/111
.wait 100
system_variable *test1/xxx*
#~rm test1/xxx/111
~rm test1/xxx/111
.wait 100
system_variable *test1/xxx*
notifier -finish test1
#~touch test1/xxx/0
~touch test1/xxx/0
file_put test1/xxx/0 0
file_info -content 0
file_get 0 test1/xxx/1
~diff test1/xxx/0 test1/xxx/1
file_kill 0
~rm test1/xxx/0
~rm test1/xxx/1
#~rmdir test1/xxx
~rmdir test1/xxx
file_put 1K*test.jpg test
file_info -recurse -d=999 test
file_info -total_items test:5*
file_info -total_items test:57*
file_get test.xxx
file_get test.xxx
file_get modules.lst.default
file_get modules.lst.default
file_get test *~test.jpg
file_kill -p=test
file_put 1K*~test.jpg test
~rm ~test.jpg
file_stats
system_variable @files_area_path test1
file_stats
system_variable @files_area_path ""
file_stats
~rm test1/ciyam_server.dat
~rm test1/ciyam_server.hdr
~rm test1/ciyam_server.idx
~rm test1/ciyam_server.tlg
file_info -recurse -d=999 test
file_info -total_blobs test
file_info -total_items test
file_info -total_encrypted test
file_crypt 8f23a8e586d7975095e740da1d43f95cfa057816e1cabddd9e627541a0b6b59d abc
file_crypt cd60cc9598f0831062978f58f3b2f04582c2a2b7efa7876dd03dcd058f2d8b74 abc
file_crypt e60982ce0b124d64f4f8c8cd2ab2b8fd9bd46c1f022aa43f4afd4618bdd056e7 abc
file_crypt 54749b4da930e6db6938a0f6393f5fa1c4dba0a148e9c23da10bed11c081b6f5 abc
file_crypt 579ad8961e4dc03ebf3965de840ff2eac2b500fde9a144d4f8d67c77ae01e686 abc
file_crypt 096b48069f1b3d0dc3a2b650661e6bbf94a5afe3a1c6694745c4505fcee8e1c2 abc
file_crypt 15515fff444eb94e0d3e0074f4c772a8bed8ec9a01bc40c691122e812adedea7 abc
file_crypt test abc
file_info -recurse -d=999 test
file_info -content 8f23a8e586d7975095e740da1d43f95cfa057816e1cabddd9e627541a0b6b59d
file_info -content 54749b4da930e6db6938a0f6393f5fa1c4dba0a148e9c23da10bed11c081b6f5
file_info -content 15515fff444eb94e0d3e0074f4c772a8bed8ec9a01bc40c691122e812adedea7
file_crypt -recurse test xxx
file_crypt -recrypt -recurse test xxx
file_crypt -recrypt -recurse -blobs_only test xxx
file_crypt -recurse test abc
file_crypt -recurse -blobs_only test abc
file_info -content test
file_info -total_blobs test
file_info -total_items test
file_info -total_encrypted test
file_crypt -recrypt -recurse -blobs_only test xxx
file_crypt -recrypt -recurse -blobs_only test xxx
file_crypt -recurse -blobs_only test abc
file_info -content test
file_crypt test abc
file_crypt -recrypt test abc
file_crypt test abc
file_info -content test
file_crypt -encrypt -cipher=cc test abc
file_crypt -decrypt -cipher=xx test abc
file_crypt -decrypt -cipher=dh test abc
file_crypt -decrypt -cipher=cc test abc
file_info -content test
file_crypt -encrypt -cipher=dh test abc
file_crypt -decrypt -cipher=cc test abc
file_crypt -decrypt -cipher=dh test abc
file_info -content test
file_get test *test1/
file_kill -recurse test
file_put 1K*test1/~test.jpg test
~rm test1/~test.jpg
session_variable @last_file_put
file_info -recurse -d=999 test
file_info -recurse -d=999 test
file_kill -recurse test
#~mkdir test2
~mkdir test2
file_archive -add test1 10MiB test1
file_archive -add test2 10MiB test2
file_archive -add test3 10MiB test3
file_archives
#~mkdir test3
~mkdir test3
file_archives -status_update
session_variable @dummy_time_stamp 20170313080001
file_put test1.jpg
session_variable @dummy_time_stamp 20170313080002
session_variable @last_file_put
file_put test2.jpg
session_variable @dummy_time_stamp 20170313080000
session_variable @last_file_put
file_put test.jpg
file_tags ts.*
file_relegate -n=1
file_tags ts.*
file_info ts.20170313080001
file_info ts.20170313080002
file_archives
file_archive -remove test1
file_archives
session_variable @dummy_time_stamp 20170313080003
file_retrieve a5ab1c26e5253fb7316b51e7f40687183714e0d683034954e1e8fc67bca42753
file_archive -add test1 10MiB test1
file_archives
file_archive -repair test1
file_archives
session_variable @dummy_time_stamp 20170313080003
file_retrieve a5ab1c26e5253fb7316b51e7f40687183714e0d683034954e1e8fc67bca42753
file_tags ts.*
file_info ts.*
file_relegate -s=9KiB test2
file_tags ts.*
file_relegate -n=1 test3
file_tags ts.*
file_archives
session_variable @dummy_time_stamp 20170313080000
file_retrieve a5ab1c26e5253fb7316b51e7f40687183714e0d683034954e1e8fc67bca42753
session_variable @dummy_time_stamp 20170313080001
file_retrieve b789eb5b80f6a8fbe9659c8d6ed04222280aa790efb7fe9e972ef8f1ede08cc9
file_get a5ab1c26e5253fb7316b51e7f40687183714e0d683034954e1e8fc67bca42753 ~test.jpg
session_variable @dummy_time_stamp 20170313080002
file_put ~test.jpg
~rm ~test.jpg
file_tags ts.*
file_kill -p=ts.*
file_tags ts.*
file_retrieve a5ab1c26e5253fb7316b51e7f40687183714e0d683034954e1e8fc67bca42753 ts.20170313080001
file_retrieve b789eb5b80f6a8fbe9659c8d6ed04222280aa790efb7fe9e972ef8f1ede08cc9 ts.20170313080002
file_raw list ts.20170313080001,ts.20170313080002 tst
file_relegate -n=2
file_tags ts*
file_info -recurse -d=999 tst
file_stats
file_kill -p=ts*
file_archive -destroy test1
file_archive -destroy test2
file_archive -destroy test3
file_archive -add test1 10MiB test1
file_archives
file_raw -text blob "Hello World!"
file_raw -text blob "This is a test."
file_raw -text list "2ccdb4c72e6c263e1dc3e5c6617bad479d267546ced55f88d6b6e4527d2e8da8 hello\n90a1a46903f42ddf0386a9c12fd67a6c109285bb8b3117ee83ed222fd0040ad3 test" root
file_info -recurse -d=2 root
file_crypt -recurse -blobs_only root password
file_info -recurse -d=2 root
file_relegate -n=2
file_stats
file_archives
session_variable @blockchain_archive_path test1
file_crypt -recurse -blobs_only root password
file_info -recurse -d=2 root
file_stats
file_kill -recurse root
file_archive -destroy test1
file_archives
file_archive -add test1 1MB test1
file_archives
file_raw -text blob 999999 test1:xxxx
FILE_HASH=$OUTPUT
file_archives
file_kill xxxx
file_retrieve $FILE_HASH xxxx
file_info xxxx
file_kill xxxx
file_raw -text blob "This is a test..." test1:xxxx
FILE_HASH=$OUTPUT
file_archives
file_info xxxx
file_kill xxxx
file_raw -text blob 499999 test1:xxxx
file_archives
file_kill xxxx
file_raw -text blob 499998 test1:xxxx
file_archives
file_kill xxxx
file_retrieve $FILE_HASH
file_put test.jpg
file_put test1.jpg
file_put test2.jpg
file_archives
file_archive -resize 2MB test1
file_raw -text blob 999999 test1:xyz
file_kill xyz
file_archives
file_archive -resize 3MB test1
file_archives
file_raw -text blob 999994 test1:xyz
file_kill xyz
#~ls -tr1 test1/c*
~ls -tr1 test1/c*
wait 100
file_raw -text blob 999999 test1:xyz
file_kill xyz
#~ls -tr1 test1/c*
~ls -tr1 test1/c*
file_archive -resize 1MB test1
file_archives
file_archive -destroy test1
session_variable @blockchain_archive_path ""
#~rmdir test1
~rmdir test1
#~rmdir test2
~rmdir test2
#~rmdir test3
~rmdir test3
session_variable @dummy_time_stamp 20170313080010
file_put test1.jpg
session_variable @dummy_time_stamp 20170313080011
file_hash ts.20170313080010
file_touch $OUTPUT
file_hash ts.20170313080011
file_kill $OUTPUT
file_put test1.jpg test1.jpg
file_put test2.jpg test2.jpg
file_raw list test1.jpg,test2.jpg test.1
file_info -content test.1
file_put test.jpg test.jpg
file_list -a=test.jpg test.1 test.2
file_info -content test.1
file_info -content test.2
file_list -sort test.2 test.3
file_info -content test.1
file_info -content test.2
file_info -content test.3
file_kill -recurse test.3
file_tag -unlink test.1,test.2
file_tags
file_put 10*test.jpg test
file_stats
file_kill -recurse test
file_stats
file_raw -text blob hello hello
file_raw -text blob goodbye goodbye
file_raw -text list "cceeb7a985ecc3dabcb4c8f666cd637f16f008e3c963db6aa6f83a7b288c54ef hello\ncceeb7a985ecc3dabcb4c8f666cd637f16f008e3c963db6aa6f83a7b288c54ef hello" test
file_list -a=goodbye test test old_test
file_info -total_items test
file_info -recurse -d=2 test
file_crypt -recurse test abc
file_info -content test
file_info -content hello
file_info -content goodbye
file_info -total_items test
file_crypt -recurse test abc
file_info -total_items test
file_info -recurse -d=2 test
file_kill test
file_kill old_test
file_kill goodbye
file_kill hello
file_put 88B*../pics/pdf_icon.gif xxx
file_info -recurse -d=2 xxx
file_info -total_items xxx
file_info -total_encrypted xxx
file_crypt b69ff7f3e051d9043be9208828100996cc71c6264d70ce8f221be3d629ed68e2 abc
file_crypt ef86dd9946ed6a67b44de7d9cc51eb244c353c0d9c624030e1aee54e7e76785a abc
file_info -recurse -d=2 xxx
file_info -total_items xxx
file_info -total_encrypted xxx
file_crypt -recurse -blobs_only xxx abc
file_info -recurse -d=2 xxx
file_info -total_items xxx
file_info -total_encrypted xxx
file_crypt -encrypt -recurse -blobs_only xxx abc
file_info -recurse -d=2 xxx
file_info -total_items xxx
file_info -total_encrypted xxx
file_crypt c611034408228e6f9e263a0c32748d0b0fb566ad2584860f3780ea378b8435f0 abc
file_info -recurse -d=2 xxx
file_info -total_items xxx
file_info -total_encrypted xxx
file_crypt -decrypt -recurse -blobs_only xxx abc
file_info -recurse -d=2 xxx
file_info -total_items xxx
file_info -total_encrypted xxx
file_kill -recurse xxx
file_stats
file_raw -text blob aaa aaa
file_raw -text blob bbb bbb
file_raw -text blob ccc ccc
file_raw -text blob ddd ddd
file_raw -text blob eee eee
file_list -a=aaa,bbb,ccc list0 !list0
file_info -content list0
file_list -a=ddd list0 list1
file_list -a=ddd list1 list2
file_list -a=ddd list2 list3
file_info -content list3
file_list -a=eee list3 list4
file_list -a=eee list4 list5
file_info -content list5
file_list -d=ddd list5 list6
file_info -content list6
file_list -d=ddd* list5 list7
file_info -content list7
file_list -d=ddd*2 list5 list8
file_info -content list8
file_list -d=bbb,ddd*,eee list5 list9
file_info -content list9
file_tags
file_kill -p=list? -x=list1,list3,list5
file_tags
file_kill -p=l*
file_tags
file_kill -p=??? -x=ccc
file_tags
file_kill ccc
file_stats
file_put 1K*mnemonics.txt x0
file_info -content x0
file_kill -recurse x0
file_put 1K*mnemonics.txt:999 x1
file_info -content x1
file_kill -recurse x1
file_put 1K*mnemonics.txt:1998 x2
file_info -content x2
file_kill -recurse x2
file_put 1K*mnemonics.txt:999+999 x3
file_info -content x3
file_kill -recurse x3
file_put 1K*mnemonics.txt:999+1998 x4
file_info -content x4
file_kill -recurse x4
file_put 1K*mnemonics.txt:1998+1998 x5
file_info -content x5
file_kill -recurse x5
file_stats
file_raw blob "test" xxx
file_raw blob "test" yyy
HASH=$OUTPUT
file_tags $HASH
session_variable @skip_tagging_if_exists 1
file_raw blob "test" zzz
file_tags $HASH
file_kill $HASH
file_stats
.quit
