get 0-39
dump detailed $TESTS_DIR/test_cache_2_b.new
put 3 "test change for 3"
put 13 "test change for 13"
put 23 "test change for 23"
put 33 "test change for 33"
throw fetch 20
get 0-39
dump detailed $TESTS_DIR/test_cache_2_c.new
throw store 2
flush old
dump detailed $TESTS_DIR/test_cache_2_d.new
flush new
get 0-39 $TESTS_DIR/test_cache_2_e.new
put 0-4 "rubbish #%d"
clear
get 0-9 $TESTS_DIR/test_cache_2_f.new
exit
