#!/bin/sh
# Copyright (c) 2013-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

../src/xrep @index.html.xrep sections=@sections.info>index.html

for i in *.txt; do cp "$i" "${i%.txt}.md"; done

# NOTE: Some SIO tags will get mistaken as HTML tags so need to escape them to avoid issues.
for i in *.md; do sed -i -e "s/<storage>/\&lt;storage\&gt;/g" -e "s/<flags>/\&lt;flags\&gt;/g"\
 -e "s/<directory>/\&lt;directory\&gt;/g" -e "s/<trace_flags>/\&lt;trace_flags\&gt;/g" -e "s/<log_files_path>/\&lt;log_files_path\&gt;/g" "$i"; done

for i in *.md; do p="${i%.*}" && echo "$p" && pandoc -i $p.md -o $p.htm; done

ls -1 *.txt | sed -e "s/\.txt$//" >~genhtml.lst

../src/xrep @gendocs.xrep prefix=../src/ docs=@~genhtml.lst>~genhtml

chmod a+x ~genhtml

./~genhtml

rm *.md
rm *.htm
rm ~genhtml
rm ~genhtml.lst
