#!/bin/sh
# Copyright (c) 2017-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: install_html [directory]"
else
 if [ ! -d "$1" ]; then
  echo "Error: Directory '$1' does not exist."
 else
  cp document.css "$1"

  cp ../pics/name_small.png "$1"
  cp ../pics/logo-gryscl-128.png "$1"
  cp ../pics/background_texture.png "$1"

  [ -d "$1/fonts" ] ||
  {
   mkdir "$1/fonts"
   ../src/unbundle -qq ../src/fonts -d "$1/fonts"
  }

  cp *.html "$1"

 fi
fi
