#!/bin/sh
# Copyright (c) 2023 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.
if [ $# -lt 2 ]; then
 echo Usage: add_user [user] [password]
else
 user_id=$1
 password=$2

 if [ "$password" = "password.info" ]; then
  password=$(<password.info)
  echo -n "temporary_password_file_for_admin_only_access" >password.info
 fi

 sudo useradd -g users -m $user_id

 sudo chpasswd <<< "$user_id:$password"
# NOTE: Use this to limit password usage for 1 day.
# sudo chage -d 1 $user_id

 sudo ln -s /home/admin/opened /home/$user_id/opened
 sudo chown -h $user_id:users /home/$user_id/opened
fi
