#!/bin/bash
# Copyright (c) 2023-2024 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: add_user [user_id] [[password]]"
else
 user_id=$1
 password=$2

 if[ ! -d /home/$user_id ]; then

  if [ "$password" = "password.info" ]; then
   password=$(<password.info)
   echo -n "temporary_password_file_for_admin_only_access" >password.info
  fi

  sudo useradd -g users -m $user_id

  tmp_file=$(mktemp --suffix ".tmp")

  echo "echo \$PID > /home/$user_id/current_pid" > $tmp_file
  echo "echo $user_id >> /home/admin/ciyam_logins" >> $tmp_file

  sudo sh -c "cat add_user_pid >> /home/$user_id/.bashrc"
  sudo sh -c "cat $tmp_file >> /home/$user_id/.bashrc"

  rm $tmp_file

  echo $user_id >> /home/admin/ciyam_users

  if [ ! "$password" = "" ]; then
   sudo chpasswd <<< "$user_id:$password"
# NOTE: Use this to limit password usage for 1 day.
#  sudo chage -d 1 $user_id
  fi

  sudo ln -s /home/admin/opened /home/$user_id/opened
  sudo chown -h $user_id:users /home/$user_id/opened
 fi
fi
