#!/bin/bash
# Copyright (c) 2025-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ "$CIYAM_USER" = "" ]; then
 CIYAM_USER=$USER
fi

ls -1 *.so | grep -v ciyam_base.so | cut -f1 -d'.' >/tmp/ciyam/ciyam_storages.tmp

if [ -f /tmp/ciyam/ciyam_storages.tmp ]; then
 copy_storage_names=

 if [ ! -f .ciyam_storages ]; then
  copy_storage_names=1
 elif ! cmp -s /tmp/ciyam/ciyam_storages.tmp .ciyam_storages &> /dev/null; then
  copy_storage_names=1
 fi

 if [ "$copy_storage_names" = "1" ]; then
  cp /tmp/ciyam/ciyam_storages.tmp .ciyam_storages
 fi
fi

# NOTE: For generating DDNS tokens
# use: "touch ciyam.<name>.ip.log"
# and then start/restart service.
if [ -f "ciyam_server.sid" ]; then
 source=ciyam_server.sid

 if [ -f "ciyam_server.sid.chk" ]; then
  source=ciyam_server.sid.chk
 fi

 seed_hash=$(sha256sum $source | head -c 64)

 for filename in ciyam.*.ip.log; do
  if [ -f "$filename" ]; then
   token=$(echo "$filename$seed_hash" | sha256sum | head -c 12)

   if [ ! -f /tmp/ciyam/$token.ip_addr ]; then
    ln -s $PWD/$filename /tmp/ciyam/$token.ip_addr
   fi
  fi
 done
fi

# NOTE: Modify the following if wanting to be notified when the CIYAM application server has been started.
#curl -H "Title: CIYAM Started" -d  "CIYAM Application Server has started." https://ntfy.domain.org/up_admin

USER_PATH=/home/$CIYAM_USER

BACKUP_PATH=$USER_PATH/backup
BACKUP_IMAGE=$USER_PATH/backup.img

if [ -d $BACKUP_PATH ]; then
 if ! mountpoint -q $BACKUP_PATH; then
  if [ -f $BACKUP_IMAGE ]; then
   sudo mount $BACKUP_IMAGE $BACKUP_PATH
  fi
 fi
fi

OPENED_PATH=$USER_PATH/opened
OPENED_IMAGE=$USER_PATH/opened.img

if [ -d $OPENED_PATH ]; then
 if ! mountpoint -q $OPENED_PATH; then
  if [ -f $OPENED_IMAGE ]; then
   sudo mount $OPENED_IMAGE $OPENED_PATH
  fi
 fi
fi

SHARED_PATH=$USER_PATH/shared
SHARED_IMAGE=$USER_PATH/shared.img

if [ -d $SHARED_PATH ]; then
 if ! mountpoint -q $SHARED_PATH; then
  if [ -f $SHARED_IMAGE ]; then
   sudo mount $SHARED_IMAGE $SHARED_PATH
  fi
 fi
fi
