#!/bin/bash
# Copyright (c) 2025 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ "$CIYAM_USER" = "" ]; then
 CIYAM_USER=$USER
fi

# NOTE: Modify the following if wanting to be notified when the CIYAM application server has been started.
#curl -H "Title: CIYAM Started" -d  "CIYAM Application Server has started." https://ntfy.domain.org/up_admin

USER_PATH=/home/$CIYAM_USER

BACKUP_PATH=$USER_PATH/backup
BACKUP_IMAGE=$USER_PATH/backup.img

if [ -d $BACKUP_PATH ]; then
 if ! mountpoint -q $BACKUP_PATH; then
  if [ -f $BACKUP_IMAGE ]; then
   sudo mount $BACKUP_IMAGE $BACKUP_PATH
  fi
 fi
fi

OPENED_PATH=$USER_PATH/opened
OPENED_IMAGE=$USER_PATH/opened.img

if [ -d $OPENED_PATH ]; then
 if ! mountpoint -q $OPENED_PATH; then
  if [ -f $OPENED_IMAGE ]; then
   sudo mount $OPENED_IMAGE $OPENED_PATH
  fi
 fi
fi

SHARED_PATH=$USER_PATH/shared
SHARED_IMAGE=$USER_PATH/shared.img

if [ -d $SHARED_PATH ]; then
 if ! mountpoint -q $SHARED_PATH; then
  if [ -f $SHARED_IMAGE ]; then
   sudo mount $SHARED_IMAGE $SHARED_PATH
  fi
 fi
fi
