#!/bin/bash
# Copyright (c) 2025-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ "$CIYAM_USER" = "" ]; then
 CIYAM_USER=$USER
fi

# NOTE: Modify the following if wanting to be notified when the CIYAM application server has been stopped.
#curl -H "Title: CIYAM Stopped" -d  "CIYAM Application Server has stopped." https://ntfy.domain.org/up_admin

USER_PATH=/home/$CIYAM_USER

BACKUP_PATH=$USER_PATH/backup

if [ -d $BACKUP_PATH ]; then
 if mountpoint -q $BACKUP_PATH; then
  sudo umount $BACKUP_PATH
 fi
fi

OPENED_PATH=$USER_PATH/opened

if [ -d $OPENED_PATH ]; then
 if mountpoint -q $OPENED_PATH; then
  sudo umount $OPENED_PATH
 fi
fi

SHARED_PATH=$USER_PATH/shared

if [ -d $SHARED_PATH ]; then
 if mountpoint -q $SHARED_PATH; then
  sudo umount $SHARED_PATH
 fi
fi
