#!/bin/bash
# Copyright (c) 2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: auto_update [name]"
else
 NAME=$1

 export CIYAM_NO_PROGRESS=1

 ./ciyam_script sync_datachain_release $NAME >~auto_update

 if grep -q "now available" ~auto_update; then
  ./ciyam_script extract_datachain_release $NAME >~auto_update

  update_output_file=auto_update.txt

  echo "$(date) [started update]" > $update_output_file

  found=

  num_files=$(wc -l < ~auto_update)

  if [ "$num_files" == "1" ]; then
   if grep -q ".tar.gz" ~auto_update; then

    found=1

    tarball=$(<~auto_update)

    folder=${tarball%".tar.gz"}

    tar -xvzf $tarball

    rm $tarball

    pushd $folder > /dev/null

    ./install >> ../$update_output_file

    popd > /dev/null

   fi
  fi

  if [ "$found" != "1" ]; then
   echo "Error: Found unexpected release information." >> $update_output_file
   cat ~auto_update >> $update_output_file
  fi

  echo "$(date) [finished update]" >> $update_output_file
 fi

 rm -f ~auto_update

fi
