#!/bin/bash
# Copyright (c) 2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ "$1" != "" ]; then
 sudo systemctl is-active ciyam >/dev/null

 if [ $? -eq 0 ]; then
  locked=$(./system_variable get @sid_locked)

  if [ $? -eq 0 ]; then
   if [ "$locked" = "" ]; then
    sudo systemd-run --property=WorkingDirectory=$PWD ./ciyam_update $1
   fi
  fi
 fi

fi
