#!/bin/bash
# Copyright (c) 2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

sleep_to_next_second( )
{
 osecs=$EPOCHSECONDS

 sleep 0.85

 # NOTE: By checking the time value
 # in seconds and using microsecond
 # sleeps to complete the "wait" it
 # is intended that after returning
 # the "next second" will have only
 # just ticked over.
 while true; do
  nsecs=$EPOCHSECONDS

  if [ "$osecs" != "$nsecs" ]; then
   break;
  fi

  sleep 0.01
 done
}

if [ $# -lt 2 ]; then
 echo "Usage: auto_loop [sleep secs[:init]] [script name] [[script arguments]]"
else
 SLEEP=$1

 SLEEP_STARTING=
 NEEDS_IMMEDIATE=

 HAS_SLEEP_BUILTIN=

 # NOTE: Will use the builtin sleep
 # if available (to avoid a process
 # being created for every sleep).
 enable sleep 2> /dev/null

 if [ $? -eq 0 ]; then
  HAS_SLEEP_BUILTIN=1
 fi

 # NOTE: If SLEEP was provided using
 # "X:Y" treat X as the SLEEP_REPEAT
 # and Y as the SLEEP_STARTING value
 # (required for immediate execution
 # followed by a regular schedule).
 if [[ $SLEEP =~ '^[0-9]+$' ]]; then
  SLEEP_REPEAT=$SLEEP
 else
  NEEDS_IMMEDIATE=1

  SLEEP_REPEAT="${SLEEP%:*}"
  SLEEP_STARTING="${SLEEP#*:}"

  if [ "$SLEEP_STARTING" = "0" ]; then
   SLEEP_STARTING=
  fi
 fi

 SCRIPT=$2

 # NOTE: Verify that the SLEEP_REPEAT value is >= 1.
 if ! (( $SLEEP_REPEAT )) then
   echo "Error: Invalid sleep value '$SLEEP_REPEAT'."
   exit 1
 fi

 shift
 shift

 ARGUMENTS=$*

 COUNTER=0

 IS_RELOADING=
 WAS_RELOADING=

 CIYAM_TMP_DIR=/tmp/ciyam

 CIYAM_PID_FILE=$CIYAM_TMP_DIR/.pid

 CIYAM_START_OR_RELOAD=1

 if [ -f $CIYAM_PID_FILE ]; then
  PID=$(<$CIYAM_PID_FILE)

  if [ "$PID" = "" ]; then
   PID=0
  fi

  while true; do

   if [ -f $CIYAM_TMP_DIR/.auto_script ]; then
    IS_RELOADING=
   else
    IS_RELOADING=1
    WAS_RELOADING=1
   fi

   if [ -d /proc/$PID ]; then

    if [ "$IS_RELOADING" = "" ] && [ "$WAS_RELOADING" = "1" ]; then
     CIYAM_START_OR_RELOAD=1

     # NOTE: If a "reload" has taken place then if needing to run
     # immediately will force the COUNTER to zero after retaining
     # the value it currently is as SLEEP_STARTING.
     if [ "$COUNTER" != "0" ] && [ "$NEEDS_IMMEDIATE" = "1" ]; then
       SLEEP_STARTING=$COUNTER

       COUNTER=0
     fi
    fi

    if [ "$COUNTER" = "0" ] && [ "$IS_RELOADING" = "" ]; then
     source ./$SCRIPT $ARGUMENTS

     WAS_RELOADING=
     CIYAM_START_OR_RELOAD=
    fi
   else
     break;
   fi

   if [ ! "$COUNTER" = "0" ]; then
    let COUNTER--

    # NOTE: If builtin sleep is unavailable
    # then just calls sleep once as it will
    # use a separate process for each call.
    if [ "$HAS_SLEEP_BUILTIN" = "" ]; then
     sleep 1
    else
     sleep_to_next_second
    fi
   else
    if [ "$SLEEP_STARTING" != "" ]; then
     COUNTER=$SLEEP_STARTING

     SLEEP_STARTING=
    else
     COUNTER=$SLEEP_REPEAT
    fi
   fi

  done

 fi
fi
