#!/bin/bash
# Copyright (c) 2022-2025 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ "$USER" = "" ]; then
 USER=$CIYAM_USER
fi

if [ "$GROUP" = "" ]; then
 GROUP=$CIYAM_GROUP
fi

USER_PATH=/home/$USER
IMAGE_NAME=backup.img

BACKUP_HEIGHT=.backup.height
IMPORTED_TIME=.imported.time

if [ "$CIYAM_USER_PATH" = "" ]; then
 CIYAM_USER_PATH=$USER_PATH
fi

BACKUP_PATH=$(./system_variable get @backup_files)

# NOTE: It is expected that the "@backup_files" system
# variable should be present but if it's not then will
# default to "$CIYAM_USER_PATH/backup" instead.
if [ "$BACKUP_PATH" = "" ]; then
 BACKUP_PATH=$CIYAM_USER_PATH/backup
fi

BACKUP_IMAGE=$CIYAM_USER_PATH/$IMAGE_NAME

BACKUP_HEIGHT_FILE=$BACKUP_PATH/$BACKUP_HEIGHT
IMPORTED_TIME_FILE=$BACKUP_PATH/$IMPORTED_TIME

TARGET_FILE=$(./system_variable get @backup_target_file)

# NOTE: If unable to umount will exit (so can call repeatedly until okay).
if [ "$TARGET_FILE" = "" ]; then
 date >Backup.txt
 echo "Preparing for restore..." >>Backup.txt

 if [ -d $BACKUP_PATH ]; then
  if mountpoint -q $BACKUP_PATH; then
   sudo umount $BACKUP_PATH
   if [ $? -ne 0 ]; then
    date >Backup.txt
    echo "NOTE: Backup files area is not currently available (please try again later)." >>Backup.txt
    date >>Backup.txt
    exit
   fi
  fi
 fi
fi

./system_variable set @backup_needed ""
./system_variable set @restore_needed ""

./system_variable set @restore_in_progress "1"

date >Backup.txt
echo "Starting restore..." >>Backup.txt

if [ "$TARGET_FILE" = "" ]; then
 sudo chown $USER:$GROUP $BACKUP_IMAGE
fi

export CIYAM_SECONDS=3
export USE_BACKUP_ARCHIVE=1
export CIYAM_FILE_NAME_ONLY=1

export CIYAM_STREAM_CIPHER=cc
export REPO_CRYPT_PASSWORD=@sid

BLOCK_TREE=$(./block_tree_hash @blockchain_backup_identity)
BACKUP_LIST=$(./tree_list $BLOCK_TREE 0 Backup | tail -n 1)

if [ ! "$TARGET_FILE" = "" ]; then
 ./export_files $BACKUP_LIST $BACKUP_PATH >>Backup.txt
else
 ./export_files $BACKUP_LIST $CIYAM_USER_PATH >>Backup.txt
fi

if [ "$TARGET_FILE" = "" ]; then
 sudo chown root:root $BACKUP_IMAGE
 sudo mount $BACKUP_IMAGE $BACKUP_PATH
 sudo chown -R $USER:$GROUP $BACKUP_PATH
 sudo chmod -R o-rx $BACKUP_PATH
fi

BLOCKCHAIN_HEIGHT=$(./system_variable get @blockchain_backup_height)

if [ -f $BACKUP_IMAGE ]; then
 echo $(date +%s) > $IMPORTED_TIME_FILE
 echo $BLOCKCHAIN_HEIGHT > $BACKUP_HEIGHT_FILE
fi

echo "Finished restore..." >>Backup.txt
date >>Backup.txt

if [ -f $BACKUP_PATH/.ciyam/Meta.backup.bun.gz ]; then
 touch .complete_restore_needed
fi

./system_variable set @restore_in_progress ""
