; Copyright (c) 2026 CIYAM Developers
;
; Distributed under the MIT/X11 software license, please refer to the file license.txt
; in the root project directory or http://www.opensource.org/licenses/mit-license.php.
;
FILE_SUFFIX=
BACKUP_DIRECTORY=
;
.system_variable @backup_files
@ifdef $OUTPUT
BACKUP_DIRECTORY=$OUTPUT
;
.system_variable @backup_target_file
@ifdef $OUTPUT
FILE_SUFFIX=:$OUTPUT
@endif
;
.system_notifier -start $BACKUP_DIRECTORY=@backup_needed$FILE_SUFFIX
@endif
