#!/bin/bash
# Copyright (c) 2022-2025 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

BLOCKCHAIN_HEIGHT=$1

if [ "$USER" = "" ]; then
 USER=$CIYAM_USER
fi

USER_PATH=/home/$USER
IMAGE_NAME=backup.img

BACKUP_TIME=.backup.time
RESTORE_NOW=.restore.now
BACKUP_HEIGHT=.backup.height
IMPORTED_TIME=.imported.time

if [ "$CIYAM_USER_PATH" = "" ]; then
 CIYAM_USER_PATH=$USER_PATH
fi

BACKUP_PATH=$CIYAM_USER_PATH/backup

BACKUP_TIME_FILE=$BACKUP_PATH/$BACKUP_TIME
RESTORE_NOW_FILE=$BACKUP_PATH/$RESTORE_NOW
BACKUP_HEIGHT_FILE=$BACKUP_PATH/$BACKUP_HEIGHT

IMPORTED_TIME_FILE=$BACKUP_PATH/$IMPORTED_TIME

skip_check_changes=

if [ -f .backup_needed ] || [ -f .prepare_backup_needed ]; then
 skip_check_changes=1
fi

if [ -f .restore_needed ] || [ -f .complete_restore_needed ]; then
 skip_check_changes=1
fi

if [ "$skip_check_changes" = "" ]; then
 if mountpoint -q $BACKUP_PATH; then

  if [ ! -f $IMPORTED_TIME_FILE ]; then
   new_change=$(find $BACKUP_PATH -path lost+found -prune -o -name "*" -type f -print | head -n 1)
  else
   new_change=$(find $BACKUP_PATH -path lost+found -prune -o -newermm $IMPORTED_TIME_FILE -name "*" -type d -print | head -n 1)
  fi

  if [ ! "$new_change" = "" ]; then
   ./system_variable set @backup_needed "1"
  fi
 fi
fi

if [ -f $BACKUP_TIME_FILE ]; then
 mv $BACKUP_TIME_FILE .
fi

if [ -f $RESTORE_NOW_FILE ]; then
 mv $RESTORE_NOW_FILE .
fi

if [ -f $BACKUP_TIME ]; then
 NOW=$(date +%s)
 TIME=$(cat $BACKUP_TIME)

 # NOTE: Allows the use of "touch" to trigger.
 if [ "$TIME" = "" ]; then
  TIME=$NOW
 fi

 if [ $NOW -ge $TIME ]; then
  rm $BACKUP_TIME
  ./run_script backup_import @errors_only=1
 fi
else
 if [ -f $RESTORE_NOW ]; then
  rm $RESTORE_NOW
  ./run_script backup_export @errors_only=1
 fi
fi
