#!/bin/sh
# Copyright (c) 2022 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

set -e

if [ -f /home/$USER/backup/.backup.time ]; then
 mv /home/$USER/backup/.backup.time .
elif [ -f .backup.time ]; then
 NOW=`date +%s`
 TIME=`cat .backup.time`

 if [ $NOW -ge $TIME ]; then
  if mountpoint -q /home/$USER/backup; then
   sudo umount /home/$USER/backup
  fi

  rm .backup.time

  rm -f /home/$USER/backup/backup.img.*

  date >Backup.txt
  echo "Starting backup..." >>Backup.txt
  ./bundle -r -ngz - /home/$USER/backup.img | split --verbose -b10G -d - /home/$USER/backup/backup.img. >>Backup.txt 2>&1

  echo "Importing backup..." >>Backup.txt
  ./import_files /home/$USER/backup Backup . backup.img. >>Backup.txt 2>&1

  echo "Finished backup..." >>Backup.txt
  date >>Backup.txt

  sudo mount /home/$USER/backup.img /home/$USER/backup
 fi
fi
