#!/bin/sh
# Copyright (c) 2022 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: block_tree_relegate [<identity> or @blockchain] [[tree tag]]"
else
 echo "<<block_tree_relegate.cin $1 $2" >~block_tree_relegate
 ./ciyam_client -echo -quiet -no_prompt -no_stderr <~block_tree_relegate
 rm ~block_tree_relegate
fi
