#!/bin/bash
# Copyright (c) 2022-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: block_tree_hash [<identity> or @blockchain_<type>_ident] [[height]]"
else
 ./ciyam_client -echo -quiet -no_prompt -no_stderr -exec="<block_tree_hash.cin $1 $2"
fi
