#!/bin/bash
# Copyright (c) 2022-2024 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: block_tree_relegate [<identity> else \"-backup\" or \"-shared\" [tree tag]]"
else
 ./ciyam_client -echo -quiet -no_prompt -no_stderr -exec="<block_tree_relegate.cin $1 $2"
fi
