#!/bin/bash
# Copyright (c) 2024-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

files=*.modules.lst

export CIYAM_EXEC_SYSTEM_APPEND=/dev/stdout

for f in $files
do
 if [ ! "$f" = "ciyam.modules.lst" ]; then
  app_name=$(basename "$f" ".modules.lst")
  app_dir=${app_name,,}

  ./ciyam_backup $app_name $app_dir
 fi
done
