#!/bin/bash
# Copyright (c) 2012-2013 CIYAM Open Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 2 -o $# -gt 3 ]; then
 echo Usage: ciyam_backup [[-trunc]] [app name] [app dir]
elif [ $# -lt 3 ] && [ "$1" = "-trunc" ]; then
 echo Usage: ciyam_backup [[-trunc]] [app name] [app dir]
elif [ "$WEBDIR" = "" ]; then
 echo Error: Missing environment variable 'WEBDIR'.
else
 opt=
 export CIYAM_STORAGE=$1
 web_path=$WEBDIR/$2
 backup_path=$PWD

 if [ "$1" = "-trunc" ]; then
  opt=$1
  export CIYAM_STORAGE=$2
  web_path=$WEBDIR/$3
 fi

 echo Starting backup...
 touch $web_path/ciyam_interface.stop
 echo \<ciyam_backup.cin $opt>~ciyam_backup.cin
 ./ciyam_client -quiet -no_prompt <~ciyam_backup.cin
 rm ~ciyam_backup.cin
 rm $web_path/ciyam_interface.stop

 pushd $web_path
 echo Adding application files to backup...
 "$backup_path/bundle" -r -q -y "$backup_path/$CIYAM_STORAGE.backup" files/*
 popd

 echo Finished backup...
fi
