#!/bin/bash
# Copyright (c) 2022-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: ciyam_command [cmd] [[arg1 [arg2 [...]]]]"
else
 ./ciyam_client -tls -quiet -no_prompt -no_stderr -exec="<ciyam_command.cin $*"
fi
