#!/bin/bash
# Copyright (c) 2012-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 2 -o $# -gt 3 ]; then
 echo "Usage: ciyam_backup [[-trunc]] [app name] [app dir]"
elif [ $# -lt 3 ] && [ "$1" = "-trunc" ]; then
 echo "Usage: ciyam_backup [[-trunc]] [app name] [app dir]"
elif [ "$WEBDIR" = "" ]; then
 echo "Error: Missing environment variable 'WEBDIR'."
else
 opt=
 export CIYAM_STORAGE=$1
 web_path=$WEBDIR/$2

 work_path=$PWD

 if [ "$1" = "-trunc" ]; then
  opt=$1
  export CIYAM_STORAGE=$2
  web_path=$WEBDIR/$3
 fi

 echo "Starting $CIYAM_STORAGE backup..."

 touch $web_path/ciyam_interface.stop

 echo "[application data]"
 ./ciyam_client -quiet -no_prompt -no_stderr -exec="<ciyam_backup.cin $opt"

 pushd $web_path >/dev/null
 if [ $? -eq 0 ]; then
  echo "[application web files]"
  if [ -f "$work_path/$CIYAM_STORAGE.backup_files.bun.gz" ]; then
   rm "$work_path/$CIYAM_STORAGE.backup_files.bun.gz"
  fi
  if [ ! "$CIYAM_STORAGE" = "Meta" ]; then
   $work_path/bundle -r -qw "$work_path/$CIYAM_STORAGE.backup_files" "files/*" -x "files/*_note_.txt" "files/*.htaccess" "files/tmp/*"
  else
   $work_path/bundle -r -qw "$work_path/$CIYAM_STORAGE.backup_files" "files/*" -x "files/*_note_.txt" "files/*.htaccess" "files/tmp/*" "files/100/105100/*" "files/100/106100/*" "files/100/135100/*"
  fi
  popd >/dev/null
 fi

 rm $web_path/ciyam_interface.stop

 echo "Finished $CIYAM_STORAGE backup..."
fi
