#!/bin/sh
# Copyright (c) 2013-2020 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.
#
# Task #T00000 - Create installation scripts for Linux and Windows

if [ `whoami` != "root" ]; then
 echo "Run this script as root."
 exit 1
fi

if [ -f /etc/init.d/ciyamd ]; then
 echo "CIYAM service has already been installed."
 exit 1
fi

cat ../.git/config | grep ciyam.git 2>&1 > /dev/null
GITCHECK=$?

if [ "$GITCHECK" != "0" ]
then
 echo 'ERROR: the current directory isnt the ciyam git! cd into the src folder of ciyam.'
 exit 1
fi

cp ciyamd /etc/init.d

ps ax | grep ciyamd | awk '{print $1}' | xargs kill 2>/dev/null

DESTPATH="/home/tux/ciyam/src"

ln -s "${DESTPATH}/ciyam_server" "/usr/bin/"
ln -s "${DESTPATH}/ciyam_base.so" "/usr/lib64/"

insserv ciyamd

sed -i "s#.WEBDIR#${WEBDIR}#" ciyam_server.sio

