#!/bin/bash
# Copyright (c) 2012-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 2 -o $# -gt 3 ]; then
 echo "Usage: ciyam_restore [[-rebuild]] [app name] [app dir]"
elif [ $# -lt 3 ] && [ "$1" = "-rebuild" ]; then
 echo "Usage: ciyam_restore [[-rebuild]] [app name] [app dir]"
elif [ "$WEBDIR" = "" ]; then
 echo "Error: Missing environment variable 'WEBDIR'."

 exit 1
else
 opt=
 work_path=$PWD

 if [ "$1" = "-rebuild" ]; then
  opt=$1
  shift
 fi

 app_name=$1
 web_path=$WEBDIR/$2

 export CIYAM_STORAGE=$app_name

 if [ -f "$work_path/$CIYAM_STORAGE.backup.bun.gz" ]; then
  echo "Starting $CIYAM_STORAGE restore..."

  echo "[application data]"
  ./ciyam_client -tls -quiet -no_prompt -exec="<ciyam_restore.cin $opt"

  if [ "$app_name" = "Meta" ]; then
   touch ciyam_base.update
  fi

  if [ -f "$work_path/$CIYAM_STORAGE.backup_files.bun.gz" ]; then
   pushd $web_path >/dev/null
   if [ $? -eq 0 ]; then
    echo "[application web files]"
    if [ "$opt" = "" ] && [ "$CIYAM_STORAGE" = "Meta" ]; then
     rm -f files/100/105100/*
     rm -f files/100/106100/*
     rm -f files/100/136100/*
    fi
    $work_path/unbundle -o -qw "$work_path/$CIYAM_STORAGE.backup_files.bun.gz" "files/*"
    popd >/dev/null
   fi
  fi

  echo "Finished $CIYAM_STORAGE restore..."
 else
  echo "Error: Backup file '$CIYAM_STORAGE.backup.bun.gz' not found."

  exit 1
 fi
fi
