#!/bin/bash
# Copyright (c) 2024-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ ! "$1" = "okay" ]; then
 echo "Usage: ciyam_restore_all [okay]"
 echo ""
 echo "WARNING: APPLICATIONS AND MODEL ARTIFACTS WILL BE DESTROYED."
else
 files=*.backup.bun.gz

 export CIYAM_EXEC_SYSTEM_APPEND=/dev/stdout

 has_meta=
 app_names=

 for f in $files
 do
  app_name=$(basename "$f" ".backup.bun.gz")
  app_dir=${app_name,,}

  if [ "$app_name" = "Meta" ]; then
   has_meta=1
  else
   if [ ! "$app_names" = "" ]; then
    app_names="$app_names,"
   fi
   app_names="$app_names$app_name"
  fi
 done

 if [ "$has_meta" = "" ]; then
  echo "Error: Missing application backup metadata."
 else
  ./ciyam_restore Meta meta

  CIYAM_BASE_UPDATE_FILE=ciyam_base.update

  tries=0
  limit=59

  sleep 0.25

  # NOTE: The "ciyam_base.update" file is created by "ciyam_restore"
  # (when called with Meta) so before continuing will need to verify
  # that the application server is ready for connections.
  while true;
  do
   if [ $tries -gt $limit ] || [ ! -f $CIYAM_BASE_UPDATE_FILE ]; then
    break;
   fi
   sleep 1
   ((tries=tries+1))
  done

  if [ $tries -gt $limit ]; then
    echo "Error: Unexpected server not available."
  else
   if [ ! "$app_names" = "" ]; then
    ./restore Meta $app_names
   fi

   for app_name in ${app_names//,/ }
   do
    app_dir=${app_name,,}

    ./unbundle -q $app_name.backup $app_name.app.vars.xrep $app_name.modules.lst
    ./gen_app_script $app_name
    ./$app_name.generate

    ./ciyam_restore $app_name $app_dir
    ./restore $app_name
   done
  fi
 fi

fi
