#!/bin/bash
# Copyright (c) 2012-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ ! -f config.h ]; then
 cp config.h.default config.h
fi
if [ ! -f config.info ]; then
 cp config.info.default config.info
fi
if [ ! -f modules.lst ]; then
 cp modules.lst.default modules.lst
fi
if [ ! -f autoscript.sio ]; then
 cp autoscript.sio.default autoscript.sio
fi
if [ ! -f manuscript.sio ]; then
 cp manuscript.sio.default manuscript.sio
fi
if [ ! -f ciyam_server.sio ]; then
 cp ciyam_server.sio.default ciyam_server.sio
fi

if [ ! -L ciyam_script.log ]; then
 ln -s .files/ciyam_script.log ciyam_script.log
fi
if [ ! -L ciyam_server.log ]; then
 ln -s .files/ciyam_server.log ciyam_server.log
fi

if [ ! -f ciyam.pem ]; then
 ./create_ciyam_pem
fi

if [ ! -f xrep ]; then
 if [ ! -f makefile ]; then
  cp makefile.tools makefile
 fi
 make xrep xvars
fi

if [ ! -f xrep ]; then
 echo "Error: Project tool 'xrep' was not found."
else
 if [ ! -f ciyam_server.sid ]; then
  ./xrep @ciyam_server.sid.sh.xrep >"~config.sh"
  chmod a+x ~config.sh
  "./~config.sh"
  rm "~config.sh"

  chmod o-r password.info
  chmod g-r password.info
 fi

 if [ ! -f ciyam.service ]; then
  ./init_service
 fi

 ./xrep @config.h.xrep >config.h.new
 ./update config.h config.h.new

 ./genmake
fi
