#!/bin/bash
# Copyright (c) 2012-2013 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ ! -f config.info ]; then
 cp config.info.default config.info
fi
if [ ! -f modules.lst ]; then
 cp modules.lst.default modules.lst
fi
if [ ! -f ciyam_server.sio ]; then
 cp ciyam_server.sio.default ciyam_server.sio
fi
if [ ! -f xrep ]; then
 if [ ! -f makefile ]; then
  cp makefile.tools makefile
 fi
 make xrep xvars
fi
if [ ! -f salt.h ]; then
 ./xrep @salt.h.xrep >salt.h
fi
./xrep @config.h.xrep >config.h.new
./update config.h config.h.new
./genmake
