#!/bin/bash
# Copyright (c) 2012-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 3 ]; then
 echo "Usage: copy_icons [package name] [package type] [app dir] [[web dir]]"
else
 if [ $# -gt 3 ]; then
  export WEBDIR=$4
 fi
 if [ "$WEBDIR" = "" ]; then
  echo Error: Missing environment variable 'WEBDIR'.

  exit 1
 else
  if [ -f $1_enum_icons.lst ]; then
   ./xrep @copy_icons.sh.xrep copy=cp name=$1 type=$2 app_dir=$3 webdir=$WEBDIR next=@$2_enum_icons.lst >"~copy_icons.sh"

   chmod a+x ~copy_icons.sh
   "./~copy_icons.sh"
   rm "~copy_icons.sh"
  fi
 fi
fi
