#!/bin/sh
# Copyright (c) 2012-2024 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo Usage: create_db [[-rebuild]] [db name] [[.]\|[password]]
else
 if [ "$1" = "-rebuild" ]; then
  db_name=$2
  rebuild=true
  password=$3
 else
  db_name=$1
  rebuild=false
  password=$2
 fi

 if [ "$MYSQL_EXEC" = "" ]; then
  MYSQL_EXEC=mysql

  if [ -f /usr/bin/mariadb ]; then
   MYSQL_EXEC=mariadb
  fi
 fi

 tmp_file=$(mktemp --suffix ".tmp")

 echo DROP DATABASE IF EXISTS $db_name\;>$tmp_file

 # NOTE: UTF-8 is not being used for 32 bit systems due to index length issues with older MySQL versions.
 if [ ! -d /usr/lib32 ] && [ ! -d /usr/lib64 ]; then
  echo CREATE DATABASE $db_name\;>>$tmp_file
 else
  echo CREATE DATABASE $db_name CHARACTER SET utf8 COLLATE utf8_bin\;>>$tmp_file
 fi

 if [ "$rebuild" = "true" ]; then
  echo GRANT USAGE ON \*.\* TO \'$db_name\'@\'localhost\'\;>>$tmp_file
  echo DROP USER \'$db_name\'@\'localhost\'\;>>$tmp_file
 fi

 echo CREATE USER \'$db_name\'@\'localhost\'\;>>$tmp_file
 echo GRANT ALL PRIVILEGES ON $db_name.\* TO \'$db_name\'@\'localhost\'\;>>$tmp_file
 echo quit>>$tmp_file

 if [ "$password" = "." ]; then
  $MYSQL_EXEC -uroot<$tmp_file
 else
  $MYSQL_EXEC -uroot -p$password<$tmp_file
 fi

 rm $tmp_file
fi
