#!/bin/sh
# Copyright (c) 2017 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo Usage: create_demo_trade_application [model name]
else
 export CIYAM_MODEL=$1
 ./ciyam_client -quiet -no_prompt < create_demo_trade_application.cin
fi
