#!/bin/sh
# Copyright (c) 2012-2020 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo Usage: create_db [[-rebuild]] [db name] [[.]\|[password]]
else
 if [ "$1" = "-rebuild" ]; then
  db_name=$2
  rebuild=true
  password=$3
 else
  db_name=$1
  rebuild=false
  password=$2
 fi

 echo DROP DATABASE IF EXISTS $db_name\;>~create_db

 # NOTE: UTF-8 is not being used for 32 bit systems due to index length issues with older MySQL versions.
 if [ ! -d /usr/lib32 ] && [ ! -d /usr/lib64 ]; then
  echo CREATE DATABASE $db_name\;>>~create_db
 else
  echo CREATE DATABASE $db_name CHARACTER SET utf8 COLLATE utf8_bin\;>>~create_db
 fi

 if [ "$rebuild" = "true" ]; then
  echo GRANT USAGE ON \*.\* TO \'$db_name\'@\'localhost\'\;>>~create_db
  echo DROP USER \'$db_name\'@\'localhost\'\;>>~create_db
 fi

 echo CREATE USER \'$db_name\'@\'localhost\'\;>>~create_db
 echo GRANT ALL PRIVILEGES ON $db_name.\* TO \'$db_name\'@\'localhost\'\;>>~create_db
 echo quit>>~create_db

 if [ "$password" = "." ]; then
  mysql -uroot<~create_db
 else
  mysql -uroot -p$password<~create_db
 fi

 rm ~create_db
fi
