#!/bin/bash
# Copyright (c) 2012-2025 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: create_db [[-rebuild]] [db name] [[.]|[password]]"
else
 if [ "$1" = "-rebuild" ]; then
  db_name=$2
  rebuild=true
  password=$3
 else
  db_name=$1
  rebuild=false
  password=$2
 fi

 if [ "$CIYAM_MYSQL" = "" ]; then
  CIYAM_MYSQL=mysql

  if [ -f /usr/bin/mariadb ]; then
   CIYAM_MYSQL=mariadb
  fi
 fi

 tmp_file=$(mktemp --suffix ".tmp")

 echo "DROP DATABASE IF EXISTS $db_name;" >$tmp_file

 echo "CREATE DATABASE $db_name CHARACTER SET utf8 COLLATE utf8_bin;" >>$tmp_file

 if [ "$rebuild" = "true" ]; then
  echo "GRANT USAGE ON *.* TO $db_name@localhost;" >>$tmp_file
  echo "DROP USER $db_name@localhost;" >>$tmp_file
 else
  echo "DROP USER IF EXISTS $db_name@localhost;" >>$tmp_file
 fi

 echo "CREATE USER $db_name@localhost;" >>$tmp_file
 echo "GRANT ALL PRIVILEGES ON $db_name.* TO $db_name@localhost;" >>$tmp_file

 if [ -f $db_name.backup.sql ]; then
  echo "USE $db_name;" >>$tmp_file
  echo "source $db_name.backup.sql" >>$tmp_file
 fi

 echo "quit" >>$tmp_file

 if [ "$password" = "." ]; then
  $CIYAM_MYSQL -uroot<$tmp_file
 else
  $CIYAM_MYSQL -uroot -p$password<$tmp_file
 fi

 rm $tmp_file

 if [ -f $db_name.backup.sql ]; then
  rm $db_name.backup.sql
 fi
fi
