#!/bin/bash
# Copyright (c) 2025-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ -f ciyam.pem ]; then
 echo "Found existing 'ciyam.pem' (remove if wanting to re-create it)."
else
 openssl req -batch -new -newkey rsa:4096 -nodes -keyout /tmp/ciyam/ciyam.key -out /tmp/ciyam/ciyam.csr &> /tmp/ciyam/create_ciyam_pem

 if [ -f /tmp/ciyam/ciyam.key ] && [ -f /tmp/ciyam/ciyam.csr ]; then
  openssl x509 -req -sha256 -days 3650 -in /tmp/ciyam/ciyam.csr -signkey /tmp/ciyam/ciyam.key -out /tmp/ciyam/ciyam.crt &> /tmp/ciyam/create_ciyam_pem

  if [ -f /tmp/ciyam/ciyam.crt ]; then
   cat /tmp/ciyam/ciyam.key /tmp/ciyam/ciyam.crt > ciyam.pem
   chmod o-r ciyam.pem
   rm /tmp/ciyam/ciyam.crt /tmp/ciyam/ciyam.csr /tmp/ciyam/ciyam.key
  else
   cat /tmp/ciyam/create_ciyam_pem
  fi
 else
  cat /tmp/ciyam/create_ciyam_pem
 fi

 rm -f /tmp/ciyam/create_ciyam_pem

fi
