; Copyright (c) 2017-2025 CIYAM Developers
;
; Distributed under the MIT/X11 software license, please refer to the file license.txt
; in the root project directory or http://www.opensource.org/licenses/mit-license.php.
;
ERROR=
;
.storage_init -admin Meta
@ifndef $ERROR
.storage_term
.storage_init Meta
.session_variable @stderr_progress 1
.pe admin 20111102 Meta Workgroup guests -101410
.storage_term
@else
@ifneq "$ERROR_FILE" ""
>$ERROR_FILE
#Error: $ERROR
>
@endif
@endif
