#!/bin/sh
# Copyright (c) 2024 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ ! "$1" = "okay" ]; then
 echo "Error: Invalid argument '$1' for 'destroy_saved_channel_info'."
else
 rm -f *.blog_info.csv.sav
fi
