#!/bin/sh
# Copyright (c) 2017-2022 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -ne 1 ]; then
 echo Usage: destroy_apps_and_models [okay]
else
 ./ciyam_client -quiet -no_prompt < destroy_apps_and_models.cin
fi
