#!/bin/bash
# Copyright (c) 2012-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: drop_db [db name] [[.]|[password]]"
else
 tmp_file=$(mktemp --suffix ".tmp")

 echo "DROP USER $1@localhost;" >$tmp_file
 echo "DROP DATABASE IF EXISTS $1;" >>$tmp_file
 echo quit>>$tmp_file

 if [ "$CIYAM_MYSQL" = "" ]; then
  CIYAM_MYSQL=mysql

  if [ -f /usr/bin/mariadb ]; then
   CIYAM_MYSQL=mariadb
  fi
 fi

 if [ "$2" = "." ]; then
  $CIYAM_MYSQL -uroot<$tmp_file
 else
  $CIYAM_MYSQL -uroot -p$2<$tmp_file
 fi

 rm $tmp_file
fi
