#!/bin/sh
# Copyright (c) 2012-2021 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo Usage: drop_db [db name] [[.]\|[password]]
else
 echo DROP USER \'$1\'@\'localhost\'\;>~drop_db
 echo DROP DATABASE IF EXISTS $1\;>>~drop_db
 echo quit>>~drop_db

 if [ "$2" = "." ]; then
  mysql -uroot<~drop_db
 else
  mysql -uroot -p$2<~drop_db
 fi

 rm ~drop_db
fi
