#!/bin/sh
# Copyright (c) 2012-2024 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo Usage: drop_db [db name] [[.]\|[password]]
else
 echo DROP USER \'$1\'@\'localhost\'\;>~drop_db
 echo DROP DATABASE IF EXISTS $1\;>>~drop_db
 echo quit>>~drop_db

 if [ "$MYSQL_EXEC" = "" ]; then
  MYSQL_EXEC=mysql

  if [ -f /usr/bin/mariadb ]; then
   MYSQL_EXEC=mariadb
  fi
 fi

 if [ "$2" = "." ]; then
  $MYSQL_EXEC -uroot<~drop_db
 else
  $MYSQL_EXEC -uroot -p$2<~drop_db
 fi

 rm ~drop_db
fi
