#!/bin/sh
# Copyright (c) 2019-2020 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 2 ]; then
 echo Usage: export_files [list tag] [start path]
else
 echo "<<export_files.cin $1 $2" >~export_files
 ./ciyam_client -echo -quiet -no_prompt -no_stderr <~export_files
 rm ~export_files
fi
