#!/bin/bash
# Copyright (c) 2019-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 2 ]; then
 echo "Usage: export_files [list tag] [start path]"
else
 ./ciyam_client -quiet -no_prompt -no_stderr -exec="<export_files.cin $1 $2"
fi
