#!/bin/bash
# Copyright (c) 2023-2025 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo Usage: export_encrypted_ods_db [app name]
else
 ./ciyam_client -echo -quiet -no_prompt -no_stderr -exec="<export_encrypted_ods_db.cin $*"
fi
