#!/bin/bash
# Copyright (c) 2012-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: ext_request [address] [[output_file]]"
else
 if [ ! "$2" = "" ]; then
  curl -s -m 8 $1 >$2
 else
  curl -s -m 8 $1
 fi
fi
