#!/bin/bash
# Copyright (c) 2012-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 2 ]; then
 echo Usage: genclass [[-rdbms]] [module name] [class name]
else
 gen_class=0
 module=$1
 classnm=$2
 full_name=$1_$2
 user_vars="user_vars=$full_name.vars.xrep"

 tmp_file=$(mktemp --suffix ".tmp")

 if [ ! "$1" = "-rdbms" ]; then
  echo model_load $1>$tmp_file
  echo generate $2>>$tmp_file

  ./modeller -quiet -no_prompt <$tmp_file
 else
  module=$2
  classnm=$3
  full_name=$2_$3
  user_vars="user_vars=$full_name.vars.xrep"
 fi

 if [ $? -eq 0 ]; then
  if [ -f $full_name.cpp ]; then
   ./extract $full_name.cpp >$tmp_file
   if [ $? -eq 0 ]; then
    ./update $full_name.cpp.xrep $tmp_file >/dev/null
   fi
  fi

  if [ -f $full_name.vars.xrep.sav ]; then
   cmp -s $full_name.vars.xrep $full_name.vars.xrep.sav
   if [ $? -eq 1 ]; then
    gen_class=1
   fi
  else
   gen_class=1
  fi

  if [ $gen_class -eq 1 ]; then
   if [ -f $full_name.cpp.xrep ]; then
    user_vars="$user_vars user_source=$full_name.cpp.xrep"
   fi

   ./xrep @ciyam_class.h.xrep $user_vars >$full_name.h.new
   if [ $? -eq 0 ]; then
    ./update $full_name.h $full_name.h.new
   fi

   ./xrep @ciyam_class.cpp.xrep $user_vars >$full_name.cpp.new
   if [ $? -eq 0 ]; then
    ./update $full_name.cpp $full_name.cpp.new
   fi

   ./xrep @ciyam_class.cms.xrep $user_vars >$full_name.cms.new
   if [ $? -eq 0 ]; then
    ./update $full_name.cms $full_name.cms.new
   fi

   cp $full_name.vars.xrep $full_name.vars.xrep.sav
  fi

  if [ -f $full_name.csv.new ]; then
   ./update $full_name.csv $full_name.csv.new
  fi

  ./genpdfs $module $classnm

  rm -f $tmp_file

  if [ -f $full_name.cpp.xrep ]; then
   rm $full_name.cpp.xrep
  fi
  if [ -f $full_name.vars.xrep ]; then
   rm $full_name.vars.xrep
  fi

 fi
fi
