#!/bin/bash
# Copyright (c) 2012-2025 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo Usage: generate [module name] [[app dir]] [[module alias]]
else
 export CIYAM_MODEL=

 # NOTE: As it is expected that 'tmp_file' will be in the current directory
 # rather than using 'mktemp' is instead using a 'tilda' prefixed UUID name.
 uuid=$(uuidgen)
 tmp_file=~$uuid

 echo -n "export CIYAM_MODEL=" >$tmp_file
 ./ciyam_client -quiet -no_prompt -no_stderr -exec="<model_key.cin $1" >>$tmp_file
 chmod a+x $tmp_file
 . ./$tmp_file

 if [ "$CIYAM_MODEL" = "" ]; then
  echo "Error: Unknown module '$1'."
 else
  echo "Starting generate..."

  ./ciyam_client -quiet -no_prompt -no_stderr -exec="<generate.cin $CIYAM_MODEL" >$tmp_file

  cat $tmp_file
  if grep -q "Error" $tmp_file || grep -q "error" $tmp_file; then
   rm $tmp_file
  else
   ./genmodule -rdbms $1 $2 $3

   ./ciyam_client -quiet -no_prompt -no_stderr -exec="<genlinks.cin $CIYAM_MODEL" >$tmp_file

   cat $tmp_file

   if [ -f manuscript.sio.new ]; then
    ./remove_identical manuscript.sio manuscript.sio.new
   fi
   echo "Finished generate..."
  fi
 fi
 rm -f $tmp_file
fi
