#!/bin/sh
# Copyright (c) 2022 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

echo "<<generate_next_block.cin $1" >~generate_next_block
./ciyam_client -echo -quiet -no_prompt -no_stderr <~generate_next_block
rm ~generate_next_block
