#!/bin/sh
# Copyright (c) 2022-2023 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: generate_next_block [<identity> else \"-hub\", \"-backup\" or \"-shared\" [[seed] [[tree tag]]]]"
else
 echo "<<generate_next_block.cin $*" >~generate_next_block
 ./ciyam_client -echo -quiet -no_prompt -no_stderr <~generate_next_block
 rm ~generate_next_block
fi
