#!/bin/bash
# Copyright (c) 2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: generate [app name]"
else
 ./gen_app_script $1

 if [ $? -eq 0 ]; then
  ./$1.generate
 fi

fi
