#!/bin/bash
# Copyright (c) 2012-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: genmodule [[-rdbms]] [model name] [[app dir]] [[module alias]]"
else
 app_dir=$2
 gen_fcgi=0
 mod_name=$1
 mod_alias=$3
 user_vars="user_vars=$1.spec.vars.xrep"

 tmp_file=$(mktemp --suffix ".tmp")

 if [ ! "$1" = "-rdbms" ]; then
  echo model_load $1>$tmp_file
  echo generate -cmd=./genclass>>$tmp_file

  ./modeller -quiet -no_prompt -no_stderr <$tmp_file
 else
  app_dir=$3
  mod_name=$2
  mod_alias=$4
  user_vars="user_vars=$2.spec.vars.xrep"
  cat $2.classes.lst | xargs -n1 ./genclass -rdbms $2
 fi

 if [ $? -eq 0 ]; then
  if [ -f $mod_name.cpp ]; then
   ./extract $mod_name.cpp >$mod_name.user.xrep
   ./extract $mod_name.cms >>$mod_name.user.xrep
  fi

  if [ -f $mod_name.user.xrep ]; then
   user_vars="$user_vars user_source=$mod_name.user.xrep"
  fi

  if [ -f $mod_name.txt.new ]; then
   ./update $mod_name.txt $mod_name.txt.new
  fi

  ./xrep @ciyam_main.cpp.xrep $user_vars >$mod_name.cpp.new

  if [ $? -eq 0 ]; then
   ./update $mod_name.cpp $mod_name.cpp.new

   ./xrep @ciyam_main.cms.xrep $user_vars >$mod_name.cms.new

   if [ $? -eq 0 ]; then
    ./update $mod_name.cms $mod_name.cms.new

    if [ -f $mod_name.user.xrep ]; then
     rm $mod_name.user.xrep
    fi

    if [ -f $mod_name.spec.vars.xrep.sav ]; then
     cmp -s $mod_name.spec.vars.xrep $mod_name.spec.vars.xrep.sav
     if [ $? -eq 1 ]; then
      gen_fcgi=1
     fi
    else
     gen_fcgi=1
    fi

    if [ $gen_fcgi -eq 1 ]; then
     ./xrep @module.fcgi.sio.xrep include=$mod_name.spec.vars.xrep >$tmp_file

     if [ $? -eq 0 ]; then
      ./update $mod_name.fcgi.sio $tmp_file
      chmod a+r $mod_name.fcgi.sio
      cp $mod_name.spec.vars.xrep $mod_name.spec.vars.xrep.sav
     fi
    fi

    ./genmake
    if [ ! "$app_dir" = "" ]; then
     ./install_module $mod_name $app_dir $mod_alias
    fi

   fi
  fi
 fi
 rm -f $tmp_file
fi
