#!/bin/bash
# Copyright (c) 2012-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ -f ./xrep ]; then
 ./xrep @makefile.sio.xrep modules=@modules.lst >makefile.sio
 if [ -f ./xvars ]; then
  ./xvars >makefile.vars.xrep
  if [ $? -eq 0 ]; then
   ./xrep @makefile.xrep >makefile.new
   if [ $? -eq 0 ]; then
    ./update makefile makefile.new
   fi
  fi
 else
  echo File 'xvars' was not found.
  fi
else
 echo File 'xrep' was not found.
fi
