#!/bin/sh
# Copyright (c) 2012-2022 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 3 ]; then
 echo "Usage: getmeta [meta type] [key val] [field1,[field2,[...]]] [[package key]]"
else

 if [ "$4" = "" ]; then
  echo \<getmeta.cin $1 $2 $3>~getmeta.cin
 else
  echo \<getmeta.cin $1 $2 $3 files/100/136100/$4.map>~getmeta.cin
 fi

 ./ciyam_client -quiet -no_prompt <~getmeta.cin

 retval=$?
 rm ~getmeta.cin

 if [ "$retval" != 0 ]; then
  exit 1;
 fi
fi
