#!/bin/bash
# Copyright (c) 2018-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -ne 3 ]; then
 echo "Usage: getmetap [meta type] [key val] [field1,[field2,[...]]]"
else
 if [ "$CIYAM_PACKAGE" = "" ]; then
  echo "Error: Missing environment variable 'CIYAM_PACKAGE'."

  exit 1
 else
  tmp_file=$(mktemp --suffix ".tmp")

  ./getmeta $* $CIYAM_PACKAGE >$tmp_file

  if [ $? -ne 0 ]; then
   cat $tmp_file
  else
   # NOTE: Remove the trailing LF if the field list is just "@key".
   if [ "$3" = "@key" ]; then
    truncate -s -1 $tmp_file
   fi
   cat $tmp_file | xclip -selection clipboard
   echo "(result is on the clipboard)"
  fi

  rm $tmp_file
 fi
fi
