#!/bin/bash
# Copyright (c) 2023-2024 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

GENERATE_HUB_BLOCK_FILE=.generate_hub_block

if lockfile -r 0 "~hub" 2>/dev/null; then

 if [ -f "$GENERATE_HUB_BLOCK_FILE" ]; then
  PEER_HUB_HEIGHT=`./system_variable get @blockchain_peer_hub_height`

  if [ ! "" = "$PEER_HUB_HEIGHT" ]; then
   ./generate_next_block -hub

   NEW_PEER_HUB_HEIGHT=`./system_variable get @blockchain_peer_hub_height`

   # NOTE: Assume generate failed if the height is unchanged.
   if [ ! "$PEER_HUB_HEIGHT" = "$NEW_PEER_HUB_HEIGHT" ]; then
    rm "$GENERATE_HUB_BLOCK_FILE"
   fi
  fi
 fi

 rm -f "~hub"
fi
