#!/bin/sh
# Copyright (c) 2021 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

echo "<<init_identity.cin" >~init_identity
./ciyam_client -echo -quiet -no_prompt -no_stderr <~init_identity
rm ~init_identity
