; Copyright (c) 2023 CIYAM Developers
;
; Distributed under the MIT/X11 software license, please refer to the file license.txt
; in the root project directory or http://www.opensource.org/licenses/mit-license.php.
;
@ifeq "$1" ""
#Usage: init_channel.cin <identity>
@else
.system_variable $$$1
@ifndef $OUTPUT
#Creating channel for identity '$1'.
<bc_gen.cin $1 @sid
.system_variable >$$$1_identity $IDENT
@endif
@endif
