#!/bin/bash
# Copyright (c) 2012-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ ! -f packages.lst ]; then
 echo Standard>packages.lst
fi
./construct @packages.lst ciyam_class.cpp.xrep
cp pre-commit ../.git/hooks
