#!/bin/bash
# Copyright (c) 2023-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ "$WEBDIR" = "" ]; then
 echo "Error: Missing environment variable 'WEBDIR'."

 exit 1
else
 MYSQL=

 if [ "$GROUP" = "" ]; then
  GROUP=$(id -gn)
 fi

 if [ -f /usr/bin/mysql ]; then
  MYSQL=mysql
 fi

 if [ -f /usr/bin/mariadb ]; then
  MYSQL=mariadb
 fi

 if [ "$MYSQL" = "" ]; then
  echo "Error: Neither MySQL (nor MariaDB) program was found (not installed?)."

  exit 1
 else
  ./xrep @ciyam.service.xrep user=$USER group=$GROUP mysql=$MYSQL webdir=$WEBDIR >ciyam.service
 fi
fi
