#!/bin/bash
# Copyright (c) 2012-2025 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 2 ]; then
 echo Usage: install_module [module name] [app dir] [[module alias]]
else
 export alias=$3
 export directory=$WEBDIR/$2

 if [ ! -f $1.fcgi.sio ]; then
  echo Error: File \'$1.fcgi.sio\' does not exist.
 elif [ ! -f $directory/fcgi.sio ]; then
  echo Error: File \'$directory/fcgi.sio\' does not exist.
 else
  cp $1.fcgi.sio $directory
  chmod a+r $directory/$1.fcgi.sio

  if [ ! "$alias" = "" ]; then
   ./xrep @module.html.xrep model_vars=$1.vars.xrep > $directory/$alias.html
  fi
 fi
fi
