#!/bin/bash
# Copyright (c) 2012-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: install_package [name]"
else
 if [ ! -f packages.lst ]; then
  ./xrep @unix_time.xrep >packages.lst
 fi

 ./xrep @install_package.xrep name=$1 packages=@packages.lst >packages.lst.new

 if [ $? -eq 0 ]; then
  ./update packages.lst packages.lst.new
  ./construct @packages.lst ciyam_class.cpp.xrep
 fi
fi
