#!/bin/bash
# Copyright (c) 2013 CIYAM Open Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 2 ]; then
 echo Usage: install_fcgi [FCGI w/o ext] [app dir] [[extra files]]
else
 tmp=$1.fcgi
 args=$1.fcgi
 directory=$WEBDIR/$2

 if [ ! -f $1 ]; then
  echo Error: File \'$1\' does not exist.
 else
  cp $1 $1.fcgi

  if [ ! -f $args ]; then
   echo Error: File \'$args\' does not exist.
  elif [ ! -f $directory/fcgi.sio ]; then
   echo Error: File \'$directory/fcgi.sio\' does not exist.
  else
  {
   if [ -f $directory/$1.kill.sh ]; then
    rm $directory/$1.kill.sh
    sleep 2
     if [ -f $directory/$1.kill.sh ]; then
      $directory/$1.kill.sh
     fi
   fi

   shift
   shift

   while [ $# -gt 0 ] ; do
    args="$args $1"
    shift
   done

   cp $args $directory
   rm $tmp
  }
  fi
 fi
fi
