#!/bin/bash
# Copyright (c) 2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

TMP_CIYAM_DIR=/tmp/ciyam

CIYAM_IRC_ALTER_FILE=$TMP_CIYAM_DIR/.irc_alter

if [ "$CIYAM_START_OR_RELOAD" = "1" ]; then
 # NOTE: Forces the script to
 # be run after first started
 # or if a reload occurs.
 touch $CIYAM_IRC_ALTER_FILE
fi

if [ -f $CIYAM_IRC_ALTER_FILE ]; then
 rm $CIYAM_IRC_ALTER_FILE

 ./ciyam_script irc_store_or_restore > /dev/null 2>&1
fi
