; Copyright (c) 2026 CIYAM Developers
;
; Distributed under the MIT/X11 software license, please refer to the file license.txt
; in the root project directory or http://www.opensource.org/licenses/mit-license.php.
;
NUM_ARGS=0
@ifdef $1
NUM_ARGS=@$NUM_ARGS+1
@endif
@ifdef $2
NUM_ARGS=@$NUM_ARGS+1
@endif
@ifdef $3
NUM_ARGS=@$NUM_ARGS+1
@endif
@ifdef $4
NUM_ARGS=@$NUM_ARGS+1
@endif
@ifdef $4
NUM_ARGS=@$NUM_ARGS+1
@endif
;
ERROR=
RETURN=
;
@ifneq "$NUM_ARGS" "5"
ERROR=Room, names, message, sender and session id are required for "irc_send_message".
@else
;
ROOM=$1
NAMES=$2
MESSAGE=$3
USER_NAME=$4
SESSION_ID=$5
;
CHANGED=
;
ENTRANCE_ROOM=0000000
STARTING_ROOM=0000001
;
@ifeq "$ROOM" "$ENTRANCE_ROOM"
ROOM=$STARTING_ROOM
@endif
;
; NOTE: Checks all MESSAGE characters
; provided are in the base64 URL set.
.regex "^([_0-9a-zA-Z]+)$$" "$MESSAGE"
;
@ifneq "$MESSAGE" "$OUTPUT"
ERROR=Invalid message format (needs to be base64).
@else
PREFIX=@substr:0,3:$MESSAGE
;
.session_variable  -id=$SESSION_ID @ip_addr
@ifeq "$OUTPUT" "::1"
PREFIX=
@elif "$OUTPUT" = "127.0.0.1"
PREFIX=
@endif
;
@ifdef $PREFIX
@ifeq "$PREFIX" "XyA"
PREFIX=
@elif "$PREFIX" = "XyB"
PREFIX=
@elif "$PREFIX" = "XyD"
PREFIX=
@endif
;
@ifdef $PREFIX
ERROR=Unexpected invalid message prefix.
@endif
;
@endif
@endif
;
@ifndef $ERROR
;
EDIT_MESSAGE=
USER_MESSAGE=
;
NAMES_LEN=@strlen:$NAMES
@ifeq "$NAMES_LEN" "13"
.regex "^([0-9]{13})$$" "$NAMES"
@ifeq "$OUTPUT" "$NAMES"
EDIT_MESSAGE=1
@endif
@endif
;
@ifdef $EDIT_MESSAGE
;
NOT_FOUND=
NOT_EDITABLE=
.session_variable @queue_irc_%ROOM%_$USER_NAME @system
;
.session_variable @gteq_session_queue $NAMES
.session_variable @queue_irc_%ROOM%_$USER_NAME *
;
@ifndef $OUTPUT
NOT_FOUND=1
@else
SOURCE_MESSAGE=%OUTPUT:1%
;
SOURCE_PARTS=@repstr: /\n:$SOURCE_MESSAGE
;
@ifneq "$NAMES" "%SOURCE_PARTS:1%"
NOT_FOUND=1
@elif "$USER_NAME" != "%SOURCE_PARTS:2%"
NOT_FOUND=1
@else
PREFIX=@substr:0,2:%SOURCE_PARTS:3%
@ifeq "$PREFIX" "Xz"
NOT_EDITABLE=1
@endif
;
@endif
;
@ifdef $NOT_FOUND
ERROR=Source message for edit was not found (or is not own).
@elif "$NOT_EDITABLE" = "1"
ERROR=Source message is designated as a system generated message.
@else
.system_gen_key -unix_unique
UNIX_UNIQUE=$OUTPUT
;
.system_variable @queue_irc_%USER_NAME%_$NAMES "$UNIX_UNIQUE $MESSAGE"
@endif
;
@endif
;
@else
ROOM_AND_USER=@strlit:%ROOM%_$USER_NAME
;
NAMES_CHECK=@repstr:./_:$NAMES
;
; NOTE: For multiple names use
; a dot separator and if found
; replaces as the following is
; illustrating:
;
; xxx.yyy
; @xxx@yyy
;
@ifneq "$NAMES" "$NAMES_CHECK"
NAMES=.$NAMES
NAMES=@repstr:./@:.$NAMES
@endif
;
; NOTE: This is for "_/?".
@ifeq "$MESSAGE" "Xy8_"
PREFIX=Xy9
@else
PREFIX=@substr:0,3:$MESSAGE
@endif
;
; NOTE: Prefix being "_/".
@ifeq "$PREFIX" "Xy9"
@ifeq "$MESSAGE" "Xy9jbGVhcg"
CHANGED=1
.system_variable @queue_irc_$ROOM_AND_USER ""
RETURN=History for '$USER_NAME' in $ROOM cleared.
@else
RETURN=Available commands are:\n
RETURN=$RETURN\nhelp (show this output)
RETURN=$RETURN\nclear (clears room history)
@endif
@else
;
.system_variable @irc_users_$ROOM
IRC_USERS=@strlit:$OUTPUT
;
@ifdef $IRC_USERS
;
@ifneq "$NAMES" "ALL"
@ifeq "$NAMES" "OTHERS"
IRC_USERS=@repstr:@%USER_NAME%@/@:%IRC_USERS%@
@elif "$NAMES" != "$USER_NAME"
IRC_USERS=@set_all_in:@:$NAMES $IRC_USERS
;
LIST=@repstr:@/,:$IRC_USERS
IRC_USERS=,$LIST
IRC_USERS=@repstr:,/@:$IRC_USERS
;
USER_MESSAGE=_:issued (message sent to $LIST)
USER_MESSAGE=@base64::$USER_MESSAGE
@endif
@endif
;
IRC_USER_SUFFIXES=@repstr:@/|:$IRC_USERS
;
.system_gen_key -unix_unique
UNIX_UNIQUE=$OUTPUT
;
@ifdef $IRC_USER_SUFFIXES
CHANGED=1
.system_variable @queue_irc_%ROOM%_$IRC_USER_SUFFIXES "$UNIX_UNIQUE $USER_NAME $MESSAGE"
@endif
;
@ifdef $USER_MESSAGE
CHANGED=1
.system_variable @queue_irc_$ROOM_AND_USER "$UNIX_UNIQUE $USER_NAME $USER_MESSAGE"
@endif
;
@endif
;
@endif
;
@endif
;
@endif
;
@endif
;
PREFIX=
ERROR_OR_RETURN=
;
@ifdef $CHANGED
.system_variable @irc_alter 1
@endif
;
@ifdef $ERROR
PREFIX=Error:$SP
ERROR_OR_RETURN=$ERROR
@elif "$RETURN" != ""
ERROR_OR_RETURN=:$RETURN
@endif
;
@ifdef $ERROR_OR_RETURN
.session_variable @args_file
@ifndef $OUTPUT
#$PREFIX$ERROR_OR_RETURN
@else
.system_variable $OUTPUT "$ERROR_OR_RETURN"
@endif
@endif
