#!/bin/bash
# Copyright (c) 2023-2025 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: kill_current_pid_for_user [user_id]"
else
 user_id=$1

 if sudo test -f "/home/$user_id/current_pid"; then

  pid=$(sudo cat /home/$user_id/current_pid)

  sudo rm "/home/$user_id/current_pid"

  CHECK=$(sudo ps -A -o "pid user" | grep "$pid $user_id")

  if [ ! "$CHECK" = "" ]; then
   sudo kill -9 $pid
  fi
 fi
fi
