#!/bin/sh
# Copyright (c) 2021-2022 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo Usage: kill_old_ts_tagged_files [tz abbr]
else
 echo "<<kill_old_ts_tagged_files.cin $1" >~kill_old_ts_tagged_files
 ./ciyam_client -echo -quiet -no_prompt -no_stderr <~kill_old_ts_tagged_files
 rm ~kill_old_ts_tagged_files
fi
