#!/bin/bash
# Copyright (c) 2012-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -ne 3 ]; then
 echo Usage: merge [base file] [first variation] [second variation]
else
 tmp_file1=$(mktemp --suffix ".tmp")
 tmp_file2=$(mktemp --suffix ".tmp")

 ./diff -q -min -rcs $1 $2 > $tmp_file1
 ./diff -q -min -rcs $1 $3 > $tmp_file2
 ./diffp -q -min $1 $tmp_file1 $tmp_file2

 rm $tmp_file1
 rm $tmp_file2
fi
