#!/bin/bash
# Copyright (c) 2019-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: merge_tags [tag name(s) and/or prefix] [[tag name]]"
else
 ./ciyam_client -echo -quiet -no_prompt -no_stderr -exec="<merge_tags.cin $1 $2"
fi
