#!/bin/sh
# Copyright (c) 2019-2022 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: merge_tags [tag name(s) and/or prefix] [[tag name]]"
else
 echo "<<merge_tags.cin $1 $2" >~merge_tags
 ./ciyam_client -echo -quiet -no_prompt -no_stderr <~merge_tags
 rm ~merge_tags
fi
