#!/bin/bash
# Copyright (c) 2012-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: meta_field [field name]"
else
 grep "^field_add.*Specification_Type.*$1 " Meta.cin
fi
