; Copyright (c) 2026 CIYAM Developers
;
; Distributed under the MIT/X11 software license, please refer to the file license.txt
; in the root project directory or http://www.opensource.org/licenses/mit-license.php.
;
NUM_ARGS=0
@ifdef $1
NUM_ARGS=@$NUM_ARGS+1
@endif
@ifdef $2
NUM_ARGS=@$NUM_ARGS+1
@endif
;
@ifneq "$NUM_ARGS" "2"
#Usage: names_extra.cin [user] "[name-1+X[ name-2+Y[ ...]]]"
@else
;
USER=$1
NAMES_AND_NUMS=$2
;
LINES=@repstr: /\n:$NAMES_AND_NUMS
;
@label NEXT
ALL_IRC_USERS=
;
@:LOOP
;
NEXT=%LINES:1%
;
@ifndef $NEXT
@label END_LOOP
@endif
;
@skip
;
@:NEXT
POS=@strpos:+:$NEXT
NPOS=@$POS+1
;
NUM=@substr:$NPOS:$NEXT
NAME=@substr:0,$POS:$NEXT
;
@ifeq "$NAME" "$USER"
@ifneq "$NUM" "1"
NAME=$I%BW%$NAME%N%
@else
NAME=%BW%$NAME%N%
@endif
@else
@ifneq "$NUM" "0"
NAME=%LO%$NAME%N%
@endif
@endif
;
@ifndef $ALL_IRC_USERS
ALL_IRC_USERS=$NAME
@else
ALL_IRC_USERS=$ALL_IRC_USERS $NAME
@endif
;
LINES=%LINES:-1%
;
!!@:LOOP
;
@:END_LOOP
;
@endif
