#!/bin/bash
# Copyright (c) 2012-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ "$1" = "-" ] || [ "$1" = "--" ]; then
 if [ "$2" != ""  ]; then
  password=$2
 else
  echo -n "Password: "
  read -s password
  echo ""
 fi

 pwd_file=/tmp/ciyam/pwd.tmp

 secs=$EPOCHSECONDS
 pass_hash=$(echo -n "$password" | sha256sum | head -c 64)

 if [ "$1" = "--" ]; then
  echo -n "$pass_hash"
 fi

 salted_hash=$(echo -n "$secs$pass_hash" | sha256sum | head -c 64)

 printf "$secs-$salted_hash" > $pwd_file

 if [ "$1" != "--" ]; then
  echo "(salted hashed password saved as '$pwd_file')"
 fi
else
 ./ciyam_client -tls -quiet -no_prompt -exec="<password.cin $1"
fi
