#!/bin/sh
# Copyright (c) 2012-2021 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

echo "<password.cin $1" >~password
./ciyam_client -tls -quiet -no_prompt <~password
rm ~password
