; Copyright (c) 2021-2026 CIYAM Developers
;
; Distributed under the MIT/X11 software license, please refer to the file license.txt
; in the root project directory or http://www.opensource.org/licenses/mit-license.php.
;
@ifneq "$1" ""
ARGS=$1
@else
.session_variable @pubkey
EXT_PUBKEY=$OUTPUT
DATA_AND_PUBKEY=@password:Enter Key/Data/Password:$EXT_PUBKEY
ARGS=@repstr:\:/ -k=:$DATA_AND_PUBKEY
@endif
;
@ifdef $ARGS
 encrypt $~ARGS
@endif
