#!/bin/sh
# Copyright (c) 2012-2019 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ "$1" = "" ]; then
 echo encrypt> ~password.cin
else
 echo encrypt $1> ~password.cin
fi
./ciyam_client -quiet -no_prompt <~password.cin
rm ~password.cin
