#!/bin/bash
# Copyright (c) 2012-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.
#
# Pre-commit hook to check correct source code formatting.

git diff --cached --name-status | while read st file; do
 # NOTE: Skip deleted files.
 if [ "$st" = 'D' ]; then
  continue;
 fi

 if [ -f ./src/check_source ]; then
  if [ "${file##*.}" = "h" ] || [ "${file##*.}" = "cpp" ]; then
   ./src/check_source -q -m$MARKER $file
   if [ $? -ne 0 ]; then
    exit 1
   fi
  fi
 else
  echo "Error: 'check_source' target is missing."
  exit 1
 fi
done
