#!/bin/sh
# Pre-commit hook to check correct source code formatting.

git diff --cached --name-status | while read st file; do
 # skip deleted files
 if [ "$st" == 'D' ]; then
  continue;
 fi
 if [ -f ./src/check_source ] || [ -f ./src/check_source.exe ]; then
  if [ "${file##*.}" = "h" ] || [ "${file##*.}" = "cpp" ]; then
   ./src/check_source -q $file
   if [ $? -ne 0 ]; then
    exit 1
   fi
  fi
 else
  echo Error: check_source target is missing.
  exit 1
 fi
done

