#!/bin/bash
# Copyright (c) 2025-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ "$WEBDIR" = "" ]; then
 echo "Error: Missing WEBDIR environment variable."

 exit
fi

if [ "$1" = "" ]; then
 echo "Usage: prepare_release [-keep_source|-remove_source]"

 exit
fi

rm_src=

if [ "$1" = "-remove_source" ]; then
 rm_src=1

 if [ "$CIYAM_CPP_OPTS" != "" ]; then
  echo "Error: Found CIYAM_CPP_OPTS (unset if really wanting to remove source code)."

  exit 1
 fi
elif [ ! "$1" = "-keep_source" ]; then
 echo "Error: Invalid option '$1' for prepare_release"

 exit 1
fi

using_service=

sudo systemctl is-active ciyam >/dev/null

if [ $? -eq 0 ]; then
 using_service=1
fi

if [ "$using_service" = "" ]; then
 touch ciyam_server.stop

 for i in {1..20}
 do
  sleep 0.5
  if [ ! -f ciyam_server.stop ]; then
   break;
  fi
 done

 if [ -f ciyam_server.stop ]; then
  echo "Error: Timed out trying to stop the CIYAM application server (is not running?)."
  rm -f ciyam_server.stop

  exit 1
 fi
else
 sudo systemctl stop ciyam
fi

make strip

if [ "$using_service" = "" ]; then
 ./ciyam_server &
 sleep 1
else
 sudo systemctl daemon-reload
 sudo systemctl start ciyam
 sudo systemctl restart apache2
fi

make release

if [ $? -ne 0 ]; then
 exit
fi

if [ "$rm_src" = "1" ]; then
 ./reconstruct_meta okay

 rm -rf $WEBDIR/meta

 cd ..
 rm -rf src

 ./install

 cd ..
 rm -rf ciyam
fi
