#!/bin/bash
# Copyright (c) 2023-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo Usage: prepare_cloned_prototype [name]
else
 if [ "$WEBDIR" = "" ]; then
  echo "Error: Missing environment variable 'WEBDIR'."
 else
  sudo systemctl stop ciyam

  rm -r .files/*
  rm -f ciyam_server.sid ciyam_server.sid.sav $WEBDIR/meta/identity.txt $WEBDIR/meta/encrypted.txt

  ./config

  sudo systemctl daemon-reload
  sudo systemctl start ciyam

  sleep 0.5

  ./restore Meta

  ./ciyam_client -quiet -no_prompt -exec="<meta_user_set_active.cin guest 0"

  sudo systemctl stop ciyam

  rm -f ciyam.pem ciyam_server.sid $1.hdr $1.idx $1.dat $1.tlg

  sudo bash -c "echo ${1,,} >/etc/hostname"
 fi
fi
