#!/bin/bash
# Copyright (c) 2023-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ ! "$CIYAM_USER" = "" ]; then
 if [ ! -f /home/$CIYAM_USER/ciyam_logins ]; then
  touch /home/$CIYAM_USER/ciyam_logins
  chmod a+w /home/$CIYAM_USER/ciyam_logins
 elif [ -s /home/$CIYAM_USER/ciyam_logins ]; then
  mv /home/$CIYAM_USER/ciyam_logins /home/$CIYAM_USER/ciyam_logins.new

  touch /home/$CIYAM_USER/ciyam_logins
  chmod a+w /home/$CIYAM_USER/ciyam_logins

  # NOTE: Ensure that a login isn't missed due to file buffering.
  sync /home/$CIYAM_USER/ciyam_logins.new

  cat /home/$CIYAM_USER/ciyam_logins.new | uniq | while read next; do ./set_random_password "$next"; done
  rm /home/$CIYAM_USER/ciyam_logins.new
 fi
fi
