#!/bin/sh
# Copyright (c) 2017 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -ne 1 ]; then
 echo Usage: reconstruct_meta [okay]
 echo ""
 echo "WARNING: APPLICATIONS AND MODEL ARTIFACTS WILL BE DESTROYED."
else
 if [ -f packages.lst ]; then
  ./construct @packages.lst ciyam_class.cpp.xrep
 fi
 ./destroy_apps_and_models $1
 ./reinstall_packages $1

 cmp -s autoscript.sio.default autoscript.sio
 if [ $? -eq 1 ]; then
  cp autoscript.sio.default autoscript.sio
 fi

 cmp -s manuscript.sio.default manuscript.sio
 if [ $? -eq 1 ]; then
  cp manuscript.sio.default manuscript.sio
 fi
fi
