#!/bin/bash
# Copyright (c) 2017-2024 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -ne 1 ]; then
 echo "Usage: reconstruct_meta [okay]"
 echo ""
 echo "WARNING: APPLICATIONS AND MODEL ARTIFACTS WILL BE DESTROYED."
else
 if [ ! "$1" = "okay" ]; then
  echo "Error: Invalid argument '$1' for 'reconstruct_meta'."
 else
  if [ -f packages.lst ]; then
   ./construct @packages.lst ciyam_class.cpp.xrep
  fi
  ./destroy_apps_and_models $1 ~reconstruct_meta
 
  if [ -f ~reconstruct_meta ]; then
   rm ~reconstruct_meta
  else
   # NOTE: Remove demo channel directories if present.
   rm -rf 7eaff0316.files
   rm -rf cce8dd5bd.files

   ./reinstall_packages $1
   ./install_packages_list $1
   ./install Meta meta
  fi
 fi
fi
