#!/bin/sh
# Copyright (c) 2017 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -ne 1 ]; then
 echo Usage: reinstall_packages [okay]
else
 grep " 135410$" Meta.log >package_lines.lst
 if [ ! -f package_lines.lst ]; then
  echo Error: File 'package_lines.lst' does not exist.
 else
  ./ciyam_client -quiet -no_prompt < destroy_meta.cin
  ./xrep @reinstall_packages.cin.xrep package_lines=@package_lines.lst >reinstall_packages.cin
  ./ciyam_client -quiet -no_prompt < reinstall_packages.cin
  rm reinstall_packages.cin
  rm package_lines.lst
 fi
fi
