#!/bin/bash
# Copyright (c) 2017-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -ne 1 ]; then
 echo Usage: reinstall_packages [okay]
else
 if [ ! "$1" = "okay" ]; then
  echo "Error: Invalid argument '$1' for 'reinstall_packages'."
 else
  ./ciyam_client -quiet -no_prompt < get_acyclic_package_types.cin

  if [ ! -f packages.acyclic.lst ]; then
   echo Error: File 'packages.acyclic.lst' does not exist.
  else
   ./ciyam_client -quiet -no_prompt < recreate_meta.cin
   ./xrep @reinstall_packages.cin.xrep packages=@packages.acyclic.lst >reinstall_packages.cin

   ./ciyam_client -quiet -no_prompt < reinstall_packages.cin

   rm reinstall_packages.cin
   rm packages.acyclic.lst
  fi
 fi
fi
