#!/bin/bash
# Copyright (c) 2012-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: remove_fcgi [app dir] [[web dir]]"
else
 if [ $# -gt 1 ]; then
  export WEBDIR=$2
 fi
 if [ "$WEBDIR" = "" ]; then
  echo "Error: Missing environment variable 'WEBDIR'."

  exit 1
 else
  if [ -d $WEBDIR/$1 ]; then
   if [ -f $WEBDIR/$1/upload.kill.sh ]; then
    rm $WEBDIR/$1/upload.kill.sh
   fi
   if [ -f $WEBDIR/$1/ciyam_interface.kill.sh ]; then
    rm $WEBDIR/$1/ciyam_interface.kill.sh
   fi

   sleep 2

   if [ -f $WEBDIR/$1/upload.kill.sh ]; then
    chmod a+x $WEBDIR/$1/upload.kill.sh
    $WEBDIR/$1/upload.kill.sh
   fi
   if [ -f $WEBDIR/$1/ciyam_interface.kill.sh ]; then
    chmod a+x $WEBDIR/$1/ciyam_interface.kill.sh
    $WEBDIR/$1/ciyam_interface.kill.sh
   fi

   rm -rf $WEBDIR/$1
  fi
 fi
fi
