#!/bin/bash
# Copyright (c) 2012-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -ne 2 ]; then
 echo "Usage: remove_identical [old file] [new file]"
else
 if [ -f $1 ]; then
  cmp -s $1 $2
  if [ $? -eq 1 ]; then
   echo "Created $2"
  else
   rm $2
  fi
 else
  echo "Created $2"
 fi
fi
