#!/bin/bash
# Copyright (c) 2024 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

export CIYAM_STOP_REGEX=" Meta 136100 [0-9]{20} 136430\$"

./restore Meta
