#!/bin/bash
# Copyright (c) 2017-2025 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: restore [[-quicker]] [app name] [[db_name[,...]]]"
elif [ $# -lt 2 ] && [ "$1" = "-quicker" ]; then
 echo "Usage: restore [[-quicker]] [app name] [[db_name[,...]]]"
else
 if [ -f packages.lst ]; then
  if [ -f ciyam_class.cpp.xrep.outline ]; then
   ./construct @packages.lst ciyam_class.cpp.xrep
  fi
 fi
 if [ ! "$1" = "-quicker" ]; then
  export CIYAM_STORAGE=$1
  export CIYAM_CREATE_DB_NAMES=$2

  ./ciyam_client -quiet -no_prompt < restore.cin
 else
  export CIYAM_STORAGE=$2
  export CIYAM_CREATE_DB_NAMES=$3

  ./ciyam_client -quiet -no_prompt < restore.cin $1
 fi
fi
