#!/bin/bash
# Copyright (c) 2024-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

# NOTE: Restore stops at the first manually created specification.
export CIYAM_STOP_REGEX="pc guest [0-9]{17} 100 115100 -g=guests "

./restore Meta
