#!/bin/sh
# Copyright (c) 2017-2021 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo Usage: restore [[-quicker]] [app name]
elif [ $# -lt 2 ] && [ "$1" = "-quicker" ]; then
 echo Usage: restore [[-quicker]] [app name]
else
 if [ -f packages.lst ]; then
  ./construct @packages.lst ciyam_class.cpp.xrep
 fi
 if [ ! "$1" = "-quicker" ]; then
  export CIYAM_STORAGE=$1
  ./ciyam_client -quiet -no_prompt < restore.cin
 else
  export CIYAM_STORAGE=$2
  ./ciyam_client -quiet -no_prompt < restore_quicker.cin
 fi
fi
