; Copyright (c) 2022-2024 CIYAM Developers
;
; Distributed under the MIT/X11 software license, please refer to the file license.txt
; in the root project directory or http://www.opensource.org/licenses/mit-license.php.
;
@ifndef $1
#NOTE: This script requires the name of a currently available 'manuscript.sio' entry.
@else
@ifndef $2
.runscript $1
@else
.runscript $1 $2
@endif
@ifdef $OUTPUT
#$OUTPUT
@endif
@endif
