#!/bin/bash
# Copyright (c) 2013 CIYAM Open Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo Usage: script [script args file] [[script name]]
else
 if [ $# -gt 1 ]; then
  echo $(date) [$2] >>$1.log
 fi
 ./ciyam_client -echo -quiet -no_prompt < $1 >>$1.log

 cat $1.log >>script.log

 rm $1
 rm $1.log
fi
