#!/bin/bash
# Copyright (c) 2022-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

demo=

if [ "$1" = "-demo" ]; then
 demo=1
 shift
fi

if [ $# -lt 2 ]; then
 echo "Usage: set_password [[-demo]] [user_id] [password]"
else
 user_id=$1
 password=$2

 if [ "$password" = "password.info" ]; then
  password=$(<password.info)

  # NOTE: Prevent password discovery via this file.
  shred "password.info"
  echo -n "temporary_password_file_for_admin_only_usage" >password.info
 fi

 password_protected=0

 # NOTE: If a file ".<user_id>_password_protected"
 # exists then will not allow a password change.
 if [ -f ".${user_id}_password_protected" ]; then
  password_protected=1
 fi

 if [ ! "$password" = "linux" ] && [ "$password_protected" = "0" ]; then
  sudo chpasswd <<< "$user_id:$password"

  if [ ! -f ciyam_server.sid ]; then

   # NOTE: Set the root password to a
   # very long random string (assumes
   # "sudo" will be used for all root
   # commands and simply ensures that
   # if the initial root password was
   # poor then it no longer matters).
   password=$(openssl rand -base64 32)
   sudo chpasswd <<< "root:$password"

   if [ "$demo" = "" ]; then
    ./resize_fs_img_files $user_id
   else
    ./resize_fs_img_files -demo $user_id
   fi
  fi
 fi
fi
