#!/bin/sh
# Copyright (c) 2022-2023 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo Usage: set_password [user] [password]
else
 if [ ! "$2" = "linux" ]; then
  echo "$1:$2" | sudo chpasswd

  sudo umount /home/$1/backup
  sudo truncate -s 93G /home/$1/backup.img
  sudo mount /home/$1/backup.img /home/$1/backup
  sudo resize2fs /home/$1/backup.img

  sudo umount /home/$1/shared
  sudo truncate -s 9500M /home/$1/shared.img
  sudo mount /home/$1/shared.img /home/$1/shared
  sudo resize2fs /home/$1/shared.img
 fi
fi
