#!/bin/bash
# Copyright (c) 2023-2025 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: set_random_password [user_id]"
else
 user_id=$1
 okay_to_change=

 if [ -f /home/admin/ciyam_users ]; then
  if grep -Fxq "$user_id" "/home/admin/ciyam_users"; then
   okay_to_change=okay
  fi
 fi

 if [ "$okay_to_change" = "okay" ]; then
  password=$(openssl rand -base64 32)
  sudo chpasswd <<< "$user_id:$password"
 else
  echo "Error: User '$user_id' is not a known CIYAM user."
 fi
fi
