#!/bin/bash
# Copyright (c) 2012-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -gt 0 ]; then
 export WEBDIR=$1
fi

if [ "$WEBDIR" = "" ]; then
 echo "Error: Missing environment variable 'WEBDIR'."

 exit 1
else
 if [ -d $WEBDIR/galleria ]; then
  echo "Error: Galleria has already been installed."

  exit 1
 else
  mkdir $WEBDIR/galleria
  ./unbundle -q galleria -d $WEBDIR/galleria
 fi
fi
