#!/bin/bash
# Copyright (c) 2012-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 2 ]; then
 echo "Usage: setup [app name] [app dir] [[web dir]]"
else
 if [ $# -gt 2 ]; then
  export WEBDIR=$3
 fi

 if [ "$WEBDIR" = "" ]; then
  echo "Error: Missing environment variable 'WEBDIR'."

  exit 1
 else
  [ -d $WEBDIR/$2 ] ||
  {
   echo "Creating $WEBDIR/$2"
   mkdir $WEBDIR/$2
   chmod 775 $WEBDIR/$2
  }
  [ -f $WEBDIR/$2/.htaccess ] ||
  {
   cp .htaccess $WEBDIR/$2
  }
  [ -d $WEBDIR/$2/css ] ||
  {
   mkdir $WEBDIR/$2/css
   ./unbundle -qq css -d $WEBDIR/$2/css
  }
  [ -d $WEBDIR/$2/fonts ] ||
  {
   mkdir $WEBDIR/$2/fonts
   ./unbundle -qq fonts -d $WEBDIR/$2/fonts
  }
  [ -d $WEBDIR/$2/images ] ||
  {
   mkdir $WEBDIR/$2/images
   ./unbundle -qq images -d $WEBDIR/$2/images
  }
  [ -d $WEBDIR/$2/popups ] ||
  {
   mkdir $WEBDIR/$2/popups
   ./unbundle -qq popups -d $WEBDIR/$2/popups
  }
  [ -d $WEBDIR/$2/scripts ] ||
  {
   mkdir $WEBDIR/$2/scripts
   ./unbundle -qq scripts -d $WEBDIR/$2/scripts
  }
  [ -d $WEBDIR/$2/html5-qrcode ] ||
  {
   mkdir $WEBDIR/$2/html5-qrcode
   ./unbundle -qq html5-qrcode -d $WEBDIR/$2/html5-qrcode
  }
  [ -f $WEBDIR/$2/ciyam_interface.js ] ||
  {
   ./xrep @ciyam_interface.js.xrep include=$1.app.vars.xrep > $WEBDIR/$2/ciyam_interface.js
  }
  [ -f $WEBDIR/$2/fcgi.sio ] ||
  {
   cp fcgi.sio $WEBDIR/$2
  }
  [ -f $WEBDIR/$2/ciyam.pem ] ||
  {
   ln -s $PWD/ciyam.pem $WEBDIR/$2
  }
  [ -f $WEBDIR/$2/upload.fcgi ] ||
  {
   cp upload $WEBDIR/$2/upload.fcgi
  }
  [ -f $WEBDIR/$2/ciyam_interface.fcgi ] ||
  {
   cp ciyam_interface $WEBDIR/$2/ciyam_interface.fcgi
  }

  ./xrep @footer.htms.xrep >footer.htms
  cat setup_files.lst | xargs -I % cp % $WEBDIR/$2
  rm footer.htms

  chmod -R g+w $WEBDIR/$2/*

 fi
fi
