#!/bin/sh
# Copyright (c) 2012-2021 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 2 ]; then
 echo Usage: setup [app name] [app dir] [[web dir]]
else
 if [ $# -gt 2 ]; then
  export WEBDIR=$3
 fi
 if [ "$WEBDIR" = "" ]; then
  echo Error: Missing environment variable 'WEBDIR'.
 else
  [ -d $WEBDIR/$2 ] ||
  {
   echo Creating $WEBDIR/$2...
   mkdir $WEBDIR/$2
   chmod 775 $WEBDIR/$2
  }
  [ -f $WEBDIR/$2/.htaccess ] ||
  {
   cp .htaccess $WEBDIR/$2
  }
  [ -d $WEBDIR/$2/css ] ||
  {
   mkdir $WEBDIR/$2/css
   ./unbundle -qq css -d $WEBDIR/$2/css
  }
  [ -d $WEBDIR/$2/images ] ||
  {
   mkdir $WEBDIR/$2/images
   ./unbundle -qq images -d $WEBDIR/$2/images
  }
  [ -d $WEBDIR/$2/popups ] ||
  {
   mkdir $WEBDIR/$2/popups
   ./unbundle -qq popups -d $WEBDIR/$2/popups
  }
  [ -d $WEBDIR/$2/scripts ] ||
  {
   mkdir $WEBDIR/$2/scripts
   ./unbundle -qq scripts -d $WEBDIR/$2/scripts
  }
  [ -f $WEBDIR/$2/ciyam_interface.js ] ||
  {
   ./xrep @ciyam_interface.js.xrep include=$1.app.vars.xrep > $WEBDIR/$2/ciyam_interface.js
  }
  [ -f $WEBDIR/$2/fcgi.sio ] ||
  {
   cp fcgi.sio $WEBDIR/$2
  }
  [ -f $WEBDIR/$2/upload.fcgi ] ||
  {
   cp upload $WEBDIR/$2/upload.fcgi
  }
  [ -f $WEBDIR/$2/ciyam_interface.pem ] ||
  {
   cp ciyam_client.pem $WEBDIR/$2/ciyam_interface.pem
  }
  [ -f $WEBDIR/$2/ciyam_interface.fcgi ] ||
  {
   cp ciyam_interface $WEBDIR/$2/ciyam_interface.fcgi
  }

  ./xrep @footer.htms.xrep >footer.htms
  cat setup_files.lst | xargs -I % cp % $WEBDIR/$2
  rm footer.htms

  chmod -R g+w $WEBDIR/$2/*

  if [ ! "$2" = "meta" ]; then
   if [ -f $WEBDIR/meta/identity.txt ] && [ ! -f $WEBDIR/$2/identity.txt ]; then
    ln -s $WEBDIR/meta/identity.txt $WEBDIR/$2/identity.txt
   fi
   if [ -f $WEBDIR/meta/encrypted.txt ] && [ ! -f $WEBDIR/$2/encrypted.txt ]; then
    ln -s $WEBDIR/meta/encrypted.txt $WEBDIR/$2/encrypted.txt
   fi
  fi

 fi
fi
