#!/bin/bash
# Copyright (c) 2022-2025 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ "$USER" = "" ]; then
 USER=$CIYAM_USER
fi

USER_PATH=/home/$USER
IMAGE_NAME=shared.img

IMPORTED_TIME=.imported.time

if [ "$CIYAM_USER_PATH" = "" ]; then
 CIYAM_USER_PATH=$USER_PATH
fi

SHARED_PATH=$(./system_variable get @shared_files)

# NOTE: It is expected that the "@shared_files" system
# variable should be present but if it's not then will
# default to "$CIYAM_USER_PATH/shared" instead.
if [ "$SHARED_PATH" = "" ]; then
 SHARED_PATH=$CIYAM_USER_PATH/shared
fi

SHARED_IMAGE=$CIYAM_USER_PATH/$IMAGE_NAME

IMPORTED_TIME_FILE=$SHARED_PATH/$IMPORTED_TIME

SHARED_DETAILS=$(./system_variable get @importing_for_identity).txt

if [ -d $SHARED_PATH ]; then
 if mountpoint -q $SHARED_PATH; then
  sudo umount $SHARED_PATH
  # NOTE: If unable to umount will exit (so can be called repeatedly until okay).
  if [ $? -ne 0 ]; then
   date >$SHARED_DETAILS
   echo "NOTE: Shared files area is not currently available (please try again later)." >>$SHARED_DETAILS
   date >>$SHARED_DETAILS
   exit
  fi
 fi
fi

./system_variable set @export_needed ""
./system_variable set @import_needed ""

date >$SHARED_DETAILS
echo "Starting import..." >>$SHARED_DETAILS

if [ -f $SHARED_IMAGE ]; then
 export CIYAM_SECONDS=12
 export USE_SHARED_ARCHIVE=1
 export CIYAM_FILE_NAME_ONLY=1

 export CIYAM_STREAM_CIPHER=cc
 export ENCRYPTED_PASSWORD=@shared_secret

 ./import_files $CIYAM_USER_PATH Shared : $IMAGE_NAME >>$SHARED_DETAILS

 ./ciyam_script tree_insert_trunks shared Shared >>$SHARED_DETAILS 2>&1
 ./ciyam_script generate_next_block -shared @sid shared >>$SHARED_DETAILS 2>&1
 ./ciyam_script block_tree_relegate -shared shared >>$SHARED_DETAILS 2>&1
fi

echo "Finished import..." >>$SHARED_DETAILS
date >>$SHARED_DETAILS

./system_variable set @shared_secret ""
./system_variable set @importing_for_identity ""

if [ -f $SHARED_IMAGE ]; then
 sudo mount $SHARED_IMAGE $SHARED_PATH
 echo $(date +%s) > $IMPORTED_TIME_FILE
fi
