#!/bin/sh
# Copyright (c) 2022-2023 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ "$USER" = "" ]; then
 USER=$CIYAM_USER
fi

USER_PATH=/home/$USER
IMAGE_NAME=shared.img

IMPORTED_TIME=.imported.time

SHARED_PATH=$USER_PATH/shared
SHARED_IMAGE=$USER_PATH/$IMAGE_NAME

IMPORTED_TIME_FILE=$SHARED_PATH/$IMPORTED_TIME

# NOTE: Use this to prevent accidentally executing the import twice.
if [ ! -f ~shared ]; then
 touch ~shared

 SHARED_DETAILS=`./system_variable get @importing_for_identity`.txt

 if [ -d $SHARED_PATH ]; then
  if mountpoint -q $SHARED_PATH; then
   sudo umount $SHARED_PATH
   # NOTE: If unable to umount will exit (so can be called repeatedly until okay).
   if [ $? -ne 0 ]; then
    date >$SHARED_DETAILS
    echo "NOTE: Shared files area is not currently available (please try again later)." >>$SHARED_DETAILS
    date >>$SHARED_DETAILS
    rm ~shared
    exit
   fi
  fi
 fi

 ./system_variable set @export_needed ""
 ./system_variable set @import_needed ""

 date >$SHARED_DETAILS
 echo "Starting import..." >>$SHARED_DETAILS

 if [ -f $SHARED_IMAGE ]; then
  export ENCRYPTED_PASSWORD=@shared_secret
  export USE_SHARED_ARCHIVE=1

  ./import_files $USER_PATH Shared : $IMAGE_NAME >>$SHARED_DETAILS
  ./tree_insert_trunks shared Shared >>$SHARED_DETAILS 2>&1
  ./generate_next_block @blockchain_shared_identity @sid shared >>$SHARED_DETAILS 2>&1
  ./block_tree_relegate @blockchain_shared_identity shared >>$SHARED_DETAILS 2>&1
 fi

 echo "Finished import..." >>$SHARED_DETAILS
 date >>$SHARED_DETAILS

 ./system_variable set @shared_secret ""
 ./system_variable set @importing_for_identity ""

 if [ -f $SHARED_IMAGE ]; then
  sudo mount $SHARED_IMAGE $SHARED_PATH
  echo `date +%s` > $IMPORTED_TIME_FILE
 fi

 rm ~shared
fi
