#!/bin/bash
# Copyright (c) 2022-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ "$USER" = "" ]; then
 USER=$CIYAM_USER
fi

USER_PATH=/home/$USER
IMAGE_NAME=shared.img

IMPORTED_TIME=.imported.time

if [ "$CIYAM_USER_PATH" = "" ]; then
 CIYAM_USER_PATH=$USER_PATH
fi

SHARED_PATH=$CIYAM_USER_PATH/shared

IMPORT_TIME_FILE=$SHARED_PATH/$IMPORT_TIME
IMPORTED_TIME_FILE=$SHARED_PATH/$IMPORTED_TIME

 if [ -f $IMPORT_TIME_FILE ]; then
  mv $IMPORT_TIME_FILE .
 fi

if mountpoint -q $SHARED_PATH; then
 if [ ! -f $IMPORTED_TIME_FILE ]; then
  NEW_CHANGE=$(find $SHARED_PATH -path lost+found -prune -o -name "*" -type f -print | head -n 1)
 else
  NEW_CHANGE=$(find $SHARED_PATH -path lost+found -prune -o -newermm $IMPORTED_TIME_FILE -name "*" -type d -print | head -n 1)
 fi

 if [ ! "$NEW_CHANGE" = "" ]; then
  ./system_variable set @export_needed ""
  ./system_variable set @import_needed "1"
 fi
fi
