#!/bin/sh
# Copyright (c) 2022 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

USER_PATH=/home/$USER
IMAGE_NAME=shared.img

IMPORTED_TIME=.imported.time

SHARED_PATH=$USER_PATH/shared

IMPORTED_TIME_FILE=$SHARED_PATH/$IMPORTED_TIME

if mountpoint -q $SHARED_PATH; then
 if [ ! -f $IMPORTED_TIME_FILE ]; then
  NEW_CHANGE=`find $SHARED_PATH -path lost+found -prune -o -name "*" -type f -print | head -n 1`
 else
  NEW_CHANGE=`find $SHARED_PATH -path lost+found -prune -o -newermm $IMPORTED_TIME_FILE -name "*" -type d -print | head -n 1`
 fi

 if [ ! "$NEW_CHANGE" = "" ]; then
  ./system_variable set @import_needed "1"
 fi
fi
