#!/bin/sh
# Copyright (c) 2022 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ "$USER" = "" ]; then
 USER=$CIYAM_USER
fi

USER_PATH=/home/$USER
IMAGE_NAME=shared.img

IMPORTED_TIME=.imported.time

SHARED_PATH=$USER_PATH/shared
SHARED_IMAGE=$USER_PATH/$IMAGE_NAME

IMPORTED_TIME_FILE=$SHARED_PATH/$IMPORTED_TIME

# NOTE: Use this to prevent accidentally executing the export twice.
if [ ! -f ~shared ]; then
 touch ~shared

 EXPORT_FOR=`./system_variable get @exporting_for_identity`.txt

 if [ -d $SHARED_PATH ]; then
  if mountpoint -q $SHARED_PATH; then
   sudo umount $SHARED_PATH
   # NOTE: If unable to umount will exit (so can be called repeatedly until okay).
   if [ $? -ne 0 ]; then
    date >$EXPORT_FOR
    echo "NOTE: Shared files area is not currently available (please try again later)." >>$EXPORT_FOR
    date >>$EXPORT_FOR
    rm ~shared
    exit
   fi
  fi
 fi

 ./system_variable set @export_needed ""
 ./system_variable set @import_needed ""

 date >$EXPORT_FOR
 echo "Starting export..." >>$EXPORT_FOR

 sudo chown $USER:www $SHARED_IMAGE

 export SECONDS=2
 export ENCRYPTED_PASSWORD=@shared_secret

 IDENTITY=`./system_variable get @export_ident`

 export CIYAM_ARCHIVE_PATH=`./ciyam_command file_archives -path_only,$IDENTITY`

 BLOCK_TREE=`./block_tree_hash $IDENTITY`
 SHARED_LIST=`./tree_list $BLOCK_TREE 0 Shared | tail -n 1`

 ./export_files $SHARED_LIST $USER_PATH >>$EXPORT_FOR

 sudo chown root:root $SHARED_IMAGE
 sudo mount $SHARED_IMAGE $SHARED_PATH

 echo `date +%s` > $IMPORTED_TIME_FILE

 echo "Finished export..." >>$EXPORT_FOR
 date >>$EXPORT_FOR

 ./system_variable set @export_ident ""
 ./system_variable set @shared_secret ""
 ./system_variable set @exporting_for_identity ""

 rm ~shared
fi
