#!/bin/sh
# Copyright (c) 2022-2023 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ "$USER" = "" ]; then
 USER=$CIYAM_USER
fi

USER_PATH=/home/$USER
IMAGE_NAME=shared.img

IMPORTED_TIME=.imported.time

SHARED_PATH=$USER_PATH/shared
SHARED_IMAGE=$USER_PATH/$IMAGE_NAME

IMPORTED_TIME_FILE=$SHARED_PATH/$IMPORTED_TIME

# NOTE: Use this to prevent accidentally executing the export twice.
if [ ! -f ~shared ]; then
 touch ~shared

 IDENTITY=`./system_variable get @export_needed`
 PEERCHAIN=`./system_variable get @exporting_for_identity`

 SHARED_DETAILS=$PEERCHAIN.txt

 if [ "$IDENTITY" = "" ]; then
  date >$SHARED_DETAILS
  echo "Error: Unexpected identity for export not found." >>$SHARED_DETAILS
  date >>$SHARED_DETAILS
  rm ~shared
  exit
 fi

 if [ "$PEERCHAIN" = "" ]; then
  date >$SHARED_DETAILS
  echo "Error: Unexpected identity exporting for not found." >>$SHARED_DETAILS
  date >>$SHARED_DETAILS
  rm ~shared
  exit
 fi

 if [ -d $SHARED_PATH ]; then
  if mountpoint -q $SHARED_PATH; then
   sudo umount $SHARED_PATH
   # NOTE: If unable to umount will exit (so can be called repeatedly until okay).
   if [ $? -ne 0 ]; then
    date >$SHARED_DETAILS
    echo "NOTE: Shared files area is not currently available (please try again later)." >>$SHARED_DETAILS
    date >>$SHARED_DETAILS
    rm ~shared
    exit
   fi
  fi
 fi

 ./system_variable set @export_needed ""
 ./system_variable set @export_needed_$PEERCHAIN ""

 ./system_variable set @import_needed ""

 date >$SHARED_DETAILS
 echo "Starting export..." >>$SHARED_DETAILS

 sudo chown $USER:www $SHARED_IMAGE

 export SECONDS=2
 export ENCRYPTED_PASSWORD=@shared_secret

 export CIYAM_ARCHIVE_PATH=`./ciyam_command file_archives -path_only,$IDENTITY`

 BLOCK_TREE=`./block_tree_hash $IDENTITY`
 SHARED_LIST=`./tree_list $BLOCK_TREE 0 Shared | tail -n 1`

 ./export_files $SHARED_LIST $USER_PATH >>$SHARED_DETAILS

 ./ciyam_command file_tag -remove,bc.$IDENTITY.shared

 sudo chown root:root $SHARED_IMAGE
 sudo mount $SHARED_IMAGE $SHARED_PATH

 echo `date +%s` > $IMPORTED_TIME_FILE

 echo "Finished export..." >>$SHARED_DETAILS
 date >>$SHARED_DETAILS

 ./system_variable set @shared_secret ""
 ./system_variable set @exporting_for_identity ""

 rm ~shared
fi
