#!/bin/sh
# Copyright (c) 2019-2022 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

git ls-files | xargs -l sha256sum > ~src_hash
cat ~src_hash | sha256sum | tr -d " -"
rm ~src_hash
