#!/bin/bash
# Copyright (c) 2022-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 2 ]; then
 echo "Usage: system_variable get|set [name] [[value]]"
else
 ./ciyam_client -echo -quiet -no_prompt -no_stderr -exec="<system_variable.cin $1 $2 $3"
fi
