#!/bin/sh
# Copyright (c) 2016-2021 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo Usage: tbitcoin [command] [[arg1 [arg2 [...]]]
else
 if [ "$TBITCOIN" = "" ]; then
  TBITCOIN="./bitcoin-cli -rpcpassword=not_what_you_think_it_is -datadir=/home/tux/.bitcoin -regtest"
 fi
 $TBITCOIN "$@"
fi
