#!/bin/bash
# Copyright (c) 2012-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -eq 1 ]; then
 ./test -q -f=files -t=../tests tests.sio test_$1
else
 ./test -q -f=files -t=../tests tests.sio
fi
