#!/bin/sh
# Copyright (c) 2024 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 3 ]; then
 echo "Usage: test_xrep_spec <spec> <section> -f <spec_arguments_file>"
 echo "   or: test_xrep_spec <spec> <section> <arg1=value1> <arg2=value2> ..."
else
 spec=$1
 section=$2

 spec_args=

 if [ "$3" == "-f" ]; then
  shift 1
  if [ ! "$3" == "" ]; then
   spec_args=`< $3 paste -sd' '`
  fi
 else
  shift 2
  spec_args=$*
 fi

 if [ "$spec_args" == "" ]; then
   echo "Error: Missing spec arguments for 'test_xrep_spec'."
 else
  ./xrep @test_spec.xrep object=$spec section=$section $spec_args
 fi

fi
