#!/bin/bash
# Copyright (c) 2024-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 3 ]; then
 echo "Usage: test_xrep_spec <spec> <section> -f <spec_arguments_file>"
 echo "   or: test_xrep_spec <spec> <section> <arg1=value1> [<arg2=value2> ...]"
else
 spec=$1
 section=$2

 spec_args=

 # NOTE: The 'spec_args' variable needs to be assigned as an array whose
 # elements need to be able to can contain spaces (hence setting IFS for
 # reading a specification arguments file to only use LFs as separators).

 if [ "$3" = "-f" ]; then
  shift 1
  if [ ! "$3" = "" ]; then
   IFS=$'\n'
   spec_args=($(< $3))
  fi
 else
  shift 2
  spec_args=("$@")
 fi

 if [ "$spec_args" = "" ]; then
  echo "Error: Missing spec arguments for 'test_xrep_spec'."

  exit 1
 else
  ./xrep @test_spec.xrep model_name=Model object=$spec section=$section "${spec_args[@]}"
 fi

fi
