
> storage_backup ciyam
Processing DDL and row data for T_Meta_User...
Processing DDL and row data for T_Meta_Workgroup...
Processing DDL and row data for T_Meta_Type...
Processing DDL and row data for T_Meta_Enum...
Processing DDL and row data for T_Meta_Enum_Item...
Processing DDL and row data for T_Meta_Model...
Processing DDL and row data for T_Meta_Class...
Processing DDL and row data for T_Meta_Field...
Processing DDL and row data for T_Meta_Index...
Processing DDL and row data for T_Meta_Modifier...
Processing DDL and row data for T_Meta_Modifier_Affect...
Processing DDL and row data for T_Meta_Procedure...
Processing DDL and row data for T_Meta_Procedure_Arg...
Processing DDL and row data for T_Meta_Relationship...
Processing DDL and row data for T_Meta_Specification_Type...
Processing DDL and row data for T_Meta_Specification...
Processing DDL and row data for T_Meta_Permission...
Processing DDL and row data for T_Meta_View_Type...
Processing DDL and row data for T_Meta_View...
Processing DDL and row data for T_Meta_View_Field_Type...
Processing DDL and row data for T_Meta_View_Field...
Processing DDL and row data for T_Meta_List_Type...
Processing DDL and row data for T_Meta_List...
Processing DDL and row data for T_Meta_List_Field_Type...
Processing DDL and row data for T_Meta_List_Field...
Processing DDL and row data for T_Meta_Auto_Code...
Processing DDL and row data for T_Meta_Module...
Processing DDL and row data for T_Meta_Application...
Processing DDL and row data for T_Meta_Specification_Field_Action...
Processing DDL and row data for T_Meta_Initial_Record...
Processing DDL and row data for T_Meta_Initial_Record_Value...
Processing DDL and row data for T_Meta_Package_Type...
Processing DDL and row data for T_Meta_Package...
Processing DDL and row data for T_Meta_Package_Option...
Processing DDL and row data for T_Meta_Application_Script...

> 