add one
add two
add xxx
add yyy
del yyy
trans
del xxx
add three
trans
in one
add abcd
trans
add efgh
commit
out
del two
rollback
in one
add first
add second
add third
out
trans
in two
add test1
add test2
add test3
trans
add test4
add test5
del test1
trans
del test2
del test3
add test6
commit
rollback
commit
out
commit
in three
add aaa
add bbb
out
trans
add four
add five
rollback
list
compress
exit
