list
export config.info.default test_ods_4_b.tmp
~diff -q test_ods_4_b.tmp test_ods_4_b.tmp
~rm test_ods_4_b.tmp
export mnemonics.txt test_ods_4_b.tmp
~diff -q mnemonics.txt test_ods_4_b.tmp
~rm test_ods_4_b.tmp
trans
del ddd
del eee
del fff
commit
list
compress
list
export config.info.default test_ods_4_b.tmp
~diff -q test_ods_4_b.tmp test_ods_4_b.tmp
~rm test_ods_4_b.tmp
export mnemonics.txt test_ods_4_b.tmp
~diff -q mnemonics.txt test_ods_4_b.tmp
~rm test_ods_4_b.tmp
exit
