file_raw -text blob "Hello World!"
file_raw -text blob "This is a test."
file_raw -text list "2ccdb4c72e6c263e1dc3e5c6617bad479d267546ced55f88d6b6e4527d2e8da8 hello\n90a1a46903f42ddf0386a9c12fd67a6c109285bb8b3117ee83ed222fd0040ad3 test" root
file_raw -text blob "at 0..."
file_raw -text blob "at 1..."
file_raw -text list "fb9677b46fbcd4bb532d10d305a5d8ebe90c9f252d655747a406ba1e7a859e25 0\n055ab3dc27be99b17779d4e5087c559f0f8743d5ac8575c5e340936b6d34ab08 1"
file_raw -text list "c158947de2088bcacd73ee2d6c5ca30200f1b4d47d409ea015c13777427a9eb1 first\nf0e0bbbf3321c7e483e3f7b4072e87791e1ec3cb74c3d4ac0db4faa765f12e32 second" root
file_hash root
file_info -content root
file_info -recurse -d=1 root
file_info -recurse -d=2 root
file_info -recurse -d=0 root
file_kill -recurse root
#~mkdir test1
~mkdir test1
file_put 1K*test.jpg test
file_info -recurse -d=999 test
file_get test *~test.jpg
file_kill -p=test
file_put 1K*~test.jpg test
~rm ~test.jpg
file_info -recurse -d=999 test
file_crypt test abc
file_info -recurse -d=999 test
file_info -content 8f23a8e586d7975095e740da1d43f95cfa057816e1cabddd9e627541a0b6b59d
file_info -content 54749b4da930e6db6938a0f6393f5fa1c4dba0a148e9c23da10bed11c081b6f5
file_info -content 15515fff444eb94e0d3e0074f4c772a8bed8ec9a01bc40c691122e812adedea7
file_crypt test xxx
file_crypt test abc
file_get test *test1/
file_kill -recurse test
file_put 1K*test1/~test.jpg test
~rm test1/~test.jpg
file_info -recurse -d=999 test
file_info -recurse -d=999 test
file_kill -recurse test
#~mkdir test2
~mkdir test2
file_archive -add test1 10MiB test1
file_archive -add test2 10MiB test2
file_archive -add test3 10MiB test3
file_archives
#~mkdir test3
~mkdir test3
file_archives -status_update
session_variable @dummy_timestamp 20170313080001
file_put test1.jpg
session_variable @dummy_timestamp 20170313080002
file_put test2.jpg
session_variable @dummy_timestamp 20170313080000
file_put test.jpg
file_tags ts.*
file_relegate -n=1
file_tags ts.*
file_archives
file_archive -remove test1
file_archives
session_variable @dummy_timestamp 20170313080003
file_retrieve a5ab1c26e5253fb7316b51e7f40687183714e0d683034954e1e8fc67bca42753
file_archive -add test1 10MiB test1
file_archives
file_archive -repair test1
file_archives
session_variable @dummy_timestamp 20170313080003
file_retrieve a5ab1c26e5253fb7316b51e7f40687183714e0d683034954e1e8fc67bca42753
file_tags ts.*
file_info ts.*
file_relegate -s=9KiB test2
file_tags ts.*
file_relegate -n=1 test3
file_tags ts.*
file_archives
session_variable @dummy_timestamp 20170313080000
file_retrieve a5ab1c26e5253fb7316b51e7f40687183714e0d683034954e1e8fc67bca42753
session_variable @dummy_timestamp 20170313080001
file_retrieve b789eb5b80f6a8fbe9659c8d6ed04222280aa790efb7fe9e972ef8f1ede08cc9
file_get a5ab1c26e5253fb7316b51e7f40687183714e0d683034954e1e8fc67bca42753 ~test.jpg
file_put ~test.jpg
~rm ~test.jpg
file_tags ts.*
file_kill -p=ts.*
file_tags ts.*
file_archive -destroy test1
file_archive -destroy test2
file_archive -destroy test3
file_archives
#~rmdir test1
~rmdir test1
#~rmdir test2
~rmdir test2
#~rmdir test3
~rmdir test3
.quit
