
> storage_restore ciyam
Creating table T_Meta_User...
Inserted 2 rows into table T_Meta_User...
Creating indexes for table T_Meta_User...
Creating table T_Meta_Workgroup...
Inserted 1 rows into table T_Meta_Workgroup...
Creating indexes for table T_Meta_Workgroup...
Creating table T_Meta_Type...
Inserted 58 rows into table T_Meta_Type...
Creating indexes for table T_Meta_Type...
Creating table T_Meta_Enum...
Inserted 14 rows into table T_Meta_Enum...
Creating indexes for table T_Meta_Enum...
Creating table T_Meta_Enum_Item...
Inserted 145 rows into table T_Meta_Enum_Item...
Creating indexes for table T_Meta_Enum_Item...
Creating table T_Meta_Model...
Inserted 1 rows into table T_Meta_Model...
Creating indexes for table T_Meta_Model...
Creating table T_Meta_Class...
Inserted 2 rows into table T_Meta_Class...
Creating indexes for table T_Meta_Class...
Creating table T_Meta_Field...
Inserted 32 rows into table T_Meta_Field...
Creating indexes for table T_Meta_Field...
Creating table T_Meta_Index...
Inserted 10 rows into table T_Meta_Index...
Creating indexes for table T_Meta_Index...
Creating table T_Meta_Modifier...
Inserted 15 rows into table T_Meta_Modifier...
Creating indexes for table T_Meta_Modifier...
Creating table T_Meta_Modifier_Affect...
Inserted 21 rows into table T_Meta_Modifier_Affect...
Creating indexes for table T_Meta_Modifier_Affect...
Creating table T_Meta_Procedure...
Inserted 1 rows into table T_Meta_Procedure...
Creating indexes for table T_Meta_Procedure...
Creating table T_Meta_Procedure_Arg...
Creating indexes for table T_Meta_Procedure_Arg...
Creating table T_Meta_Relationship...
Inserted 1 rows into table T_Meta_Relationship...
Creating indexes for table T_Meta_Relationship...
Creating table T_Meta_Specification_Type...
Inserted 341 rows into table T_Meta_Specification_Type...
Creating indexes for table T_Meta_Specification_Type...
Creating table T_Meta_Specification...
Inserted 63 rows into table T_Meta_Specification...
Creating indexes for table T_Meta_Specification...
Creating table T_Meta_Permission...
Creating indexes for table T_Meta_Permission...
Creating table T_Meta_View_Type...
Inserted 3 rows into table T_Meta_View_Type...
Creating indexes for table T_Meta_View_Type...
Creating table T_Meta_View...
Inserted 2 rows into table T_Meta_View...
Creating indexes for table T_Meta_View...
Creating table T_Meta_View_Field_Type...
Inserted 3 rows into table T_Meta_View_Field_Type...
Creating indexes for table T_Meta_View_Field_Type...
Creating table T_Meta_View_Field...
Inserted 18 rows into table T_Meta_View_Field...
Creating indexes for table T_Meta_View_Field...
Creating table T_Meta_List_Type...
Inserted 9 rows into table T_Meta_List_Type...
Creating indexes for table T_Meta_List_Type...
Creating table T_Meta_List...
Inserted 2 rows into table T_Meta_List...
Creating indexes for table T_Meta_List...
Creating table T_Meta_List_Field_Type...
Inserted 10 rows into table T_Meta_List_Field_Type...
Creating indexes for table T_Meta_List_Field_Type...
Creating table T_Meta_List_Field...
Inserted 9 rows into table T_Meta_List_Field...
Creating indexes for table T_Meta_List_Field...
Creating table T_Meta_Auto_Code...
Inserted 1 rows into table T_Meta_Auto_Code...
Creating indexes for table T_Meta_Auto_Code...
Creating table T_Meta_Module...
Creating indexes for table T_Meta_Module...
Creating table T_Meta_Application...
Creating indexes for table T_Meta_Application...
Creating table T_Meta_Specification_Field_Action...
Creating indexes for table T_Meta_Specification_Field_Action...
Creating table T_Meta_Initial_Record...
Inserted 6 rows into table T_Meta_Initial_Record...
Creating indexes for table T_Meta_Initial_Record...
Creating table T_Meta_Initial_Record_Value...
Inserted 140 rows into table T_Meta_Initial_Record_Value...
Creating indexes for table T_Meta_Initial_Record_Value...
Creating table T_Meta_Package_Type...
Inserted 4 rows into table T_Meta_Package_Type...
Creating indexes for table T_Meta_Package_Type...
Creating table T_Meta_Package...
Inserted 2 rows into table T_Meta_Package...
Creating indexes for table T_Meta_Package...
Creating table T_Meta_Package_Option...
Inserted 14 rows into table T_Meta_Package_Option...
Creating indexes for table T_Meta_Package_Option...
Creating table T_Meta_Application_Script...
Inserted 3 rows into table T_Meta_Application_Script...
Creating indexes for table T_Meta_Application_Script...

> 