#!/bin/sh
# Copyright (c) 2017-2020 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo Usage: tlitecoin [command] [[arg1 [arg2 [...]]]
else
 if [ "$TLITECOIN" = "" ]; then
  TLITECOIN="./litecoin-cli -rpcpassword=not_what_you_think_it_is -datadir=/home/tux/.litecoin -regtest"
 fi
 $TLITECOIN "$@"
fi
