#!/bin/bash
# Copyright (c) 2017-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: train [name]"
else
 ./ciyam_client -tls -quiet -no_prompt < train_$1_algos.cin
fi
