#!/bin/sh
# Copyright (c) 2019-2022 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 5 ]; then
 echo "Usage: tree_insert_file [tree tag] [trunk name] [branch expr] [sub-directory path] [file name] [base path] [[tag prefix]]"
else
 echo "<<tree_insert_file.cin $1 $2 $3 $4 $5 $6 $7" >~tree_insert_file
 ./ciyam_client -echo -quiet -no_prompt -no_stderr <~tree_insert_file
 rm ~tree_insert_file
fi
