#!/bin/sh
# Copyright (c) 2019 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: tree_list_tags [tree tag] [[branch type] [[tag branch expression]]]"
else
 echo "<<tree_list_tags.cin $1 $2 $3" >~tree_list_tags
 ./ciyam_client -echo -quiet -no_prompt -no_stderr <~tree_list_tags
 rm ~tree_list_tags
fi
