#!/bin/bash
# Copyright (c) 2019-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 3 ]; then
 echo "Usage: tree_fetch_variable [tree tag] [branch expr] [variable name]"
else
 ./ciyam_client -echo -quiet -no_prompt -no_stderr -exec="<tree_fetch_variable.cin $1 $2 $3"
fi
