#!/bin/sh
# Copyright (c) 2021-2023 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 2 ]; then
 echo "Usage: tree_insert_trunks [tree tag] [trunk tag(s)]"
else
 echo "<<tree_insert_trunks.cin $1 $2" >~tree_insert_trunks
 ./ciyam_client -echo -quiet -no_prompt -no_stderr <~tree_insert_trunks
 rm ~tree_insert_trunks
fi
