#!/bin/bash
# Copyright (c) 2021-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: tree_crypt [[-repo]|[-repo_decrypt]|[-repo_encrypt] [repository]] [tag or hash] [[password]]"
else
 ./ciyam_client -echo -quiet -no_prompt -no_stderr -exec="<tree_crypt.cin $1 $2 $3 $4"
fi
