#!/bin/bash
# Copyright (c) 2021-2025 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 2 ]; then
 echo "Usage: tree_insert_trunks [tree tag] [trunk tag(s)]"
else
 ./ciyam_client -echo -quiet -no_prompt -no_stderr -exec="<tree_insert_trunks.cin $1 $2"
fi
