#!/bin/sh
# Copyright (c) 2021-2022 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: tree_crypt [[:]tag name] [[password]]]"
else
 echo "<<tree_crypt.cin $1 $2" >~tree_crypt
 ./ciyam_client -echo -quiet -no_prompt -no_stderr <~tree_crypt
 rm ~tree_crypt
fi
