#!/bin/sh
# Copyright (c) 2019-2020 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 1 ]; then
 echo "Usage: tree_list [tag name] [[depth [prefix]]]"
else
 echo "<<tree_list.cin $1 $2 $3" >~tree_list
 ./ciyam_client -echo -quiet -no_prompt -no_stderr <~tree_list
 rm ~tree_list
fi
