@ifeq "$1" ""
#Usage: tree_crypt.cin [-repo] <tag_or_hash> [<password>]
@else
;
ARGS=
@ifneq "$1" "-repo"
TAG_OR_HASH=$1
ARGS=$2
OPT=-blobs_only
@else
TAG_OR_HASH=$2
ARGS=$3
OPT=-blobs_only_repo
@endif
;
@ifeq "$ARGS" ""
.session_variable @pubkey
EXT_PUBKEY=$OUTPUT
DATA_AND_PUBKEY=@password:Enter Password:$EXT_PUBKEY
ARGS=@repstr:\:/ -k=:$DATA_AND_PUBKEY
@endif
;
@ifdef $ARGS
 .file_crypt -recurse $OPT $TAG_OR_HASH $~ARGS
@endif
@endif
