#!/bin/sh
# Copyright (c) 2022 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 2 ]; then
 echo "Usage: tree_remove_trunks [tree tag] [trunk item(s)]"
else
 echo "<<tree_remove_trunks.cin $1 $2" >~tree_remove_trunks
 ./ciyam_client -echo -quiet -no_prompt -no_stderr <~tree_remove_trunks
 rm ~tree_remove_trunks
fi
