#!/bin/bash
# Copyright (c) 2019-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 5 ]; then
 echo "Usage: tree_insert_tag [tree tag] [trunk name] [branch expr] [item name] [tag name]"
else
 ./ciyam_client -echo -quiet -no_prompt -no_stderr -exec="<tree_insert_tag.cin $1 $2 $3 $4 $5"
fi
