#!/bin/sh
# Copyright (c) 2019-2021 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 2 ]; then
 echo "Usage: tree_list_files [tree tag] [branch type] [[branch tree expression]]"
else
 echo "<<tree_list_files.cin $1 $2 $3" >~tree_list_files
 ./ciyam_client -echo -quiet -no_prompt -no_stderr <~tree_list_files
 rm ~tree_list_files
fi
