#!/bin/sh
# Copyright (c) 2019-2022 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -lt 5 ]; then
 echo "Usage: tree_insert_tag [tree tag] [trunk name] [branch expr] [item name] [tag name]"
else
 echo "<<tree_insert_tag.cin $1 $2 $3 $4 \"$5\"" >~tree_insert_tag
 ./ciyam_client -echo -quiet -no_prompt -no_stderr <~tree_insert_tag
 rm ~tree_insert_tag
fi
