#!/bin/bash
# Copyright (c) 2021-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

./ciyam_client -quiet -no_prompt -no_stderr -exec="<unlock_identity.cin $*"
