#!/bin/bash
# Copyright (c) 2022-2025 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

# NOTE: Replace with a specific year or leave it empty to derive the year from 'date'.
DATEYEAR=""

if [ "$DATEYEAR" = "" ]; then
 DATEYEAR=$(date +%Y)
fi

for f in *.package.bun.gz
do
 echo "Processing $f..."

 ./unbundle -l -q $f | grep -Ev "\.jpg$|\.png$|\.info$|\.4WX.cin$|\.4WX.txt$|\.cpp.xrep$|\.abbrs.txt$|\.email.txt$|\.spec.xrep$|_extkeys.txt$|_enum_icons.lst$|\.data.package.sio$" >"~update_package_copyright_year"

 cat "~update_package_copyright_year" | xargs -I{} sed -i "s/Copyright (c) \([0-9]\{4\}\) CIYAM Developers/Copyright (c) \1-${DATEYEAR} CIYAM Developers/" "{}"
 cat "~update_package_copyright_year" | xargs -I{} sed -i "s/Copyright (c) \([0-9]\{4\}\)-\([0-9]\{4\}\) CIYAM Developers/Copyright (c) \1-${DATEYEAR} CIYAM Developers/" "{}"

 FILES=$(cat "~update_package_copyright_year" | tr '\n' ' ')

 ./bundle -q $f $FILES

 echo

 rm "~update_package_copyright_year"
done
