#!/bin/bash
# Copyright (c) 2012-2026 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ $# -ne 2 ]; then
 echo Usage: update [dest file] [temp file]
else
 if [ -f $1 ]; then
  cmp -s $1 $2
  if [ $? -eq 1 ]; then
   mv $2 $1
   echo Updated $1
  else
   rm $2
  fi
 else
  mv $2 $1
  echo Created $1
 fi
fi
