#!/bin/bash
# Copyright (c) 2023-2025 CIYAM Developers
#
# Distributed under the MIT/X11 software license, please refer to the file license.txt
# in the root project directory or http://www.opensource.org/licenses/mit-license.php.

if [ "$WEBDIR" = "" ]; then
  echo "Error: Missing environment variable 'WEBDIR'."
else
 if [ ! -f ciyam_server.sid.sav ]; then
  echo "Error: Saved identity (ciyam_server.sid.sav) was not found."
 else
  ./restore_identity > /dev/null
  sudo systemctl restart ciyam
  sleep 1
  ./reconstruct_meta okay
  ./save_identity
  ./erase_identity > /dev/null
 fi
fi
